sudo: required
dist: xenial
language: cpp

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
  - sudo apt-get update

install:
  - sudo apt-get install qt58base qt58svg qt58charts-no-lgpl qt58xmlpatterns qtbase5-dev qtdeclarative5-dev
  - source /opt/qt58/bin/qt58-env.sh
services:
  - xvfb

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - g++-8
            - boost1.68
            - valgrind
      env:
      - C_COMPILER=gcc-8
      - CXX_COMPILER=g++-8

script:
  - mkdir build
  - cd build
  - env CC=${C_COMPILER} CXX=${CXX_COMPILER} cmake .. -DENABLE_COVERAGE:BOOL=TRUE -DCMAKE_BUILD_TYPE=DEBUG
  - echo "We have" `nproc` "cores here"
  - make -j `nproc`
  - ctest -j `nproc` -V

after_success:
  - bash <(curl -s https://codecov.io/bash) -x gcov-8
