#pragma once

#include <string>
#include <vector>

const std::vector<std::string> testParsedGlossaryHtmlContent{
    ": to go or come after and bring or take back",
    "// fetch a doctor",
    ": derive, deduce",
    "// fetch analogies from nature",
    ": to cause to come",
    "// one shot fetched down",
    ": to bring in (a price or similar return) : realize",
    "// The hogs fetched a good price at the market.",
    ": interest, attract",
    "// … he doesn't fetch the girls like William …",
    ": to give (a blow) by striking : deal",
    "// fetch him a clip on the chin",
    ": bring about, accomplish",
    ": to take in : draw",
    "// sat fetching her breath in dry sobs",
    ": to bring forth : heave",
    "// fetch a sigh",
    ": to reach by sailing especially against the wind or tide",
    "// fetch the harbor before the storm breaks",
    ": to arrive at : reach",
    "// fetched home after a long ride",
    ": to get and bring something",
    ": to retrieve killed game",
    ": to take a roundabout way : circle",
    ": to hold a course on a body of water",
    "// fetch to windward",
    ": veer",
    ": trick, stratagem",
    ": an act or instance of fetching",
    ": the distance along open water or land over which the wind blows",
    ": the distance traversed by waves without obstruction",
    ": doppelgänger sense 2",
    "; If you throw the ball the dog will fetch it.",
    "; Hunting dogs are trained to fetch.",
    "; This table should fetch quite a bit at auction.",
    "; The house fetched more than we expected.",
    ": to go after and bring back (someone or something)",
    ": to be sold for (an amount of money)",
    ": to go after and bring back",
    ": to bring as a price : sell for",
    "// The artwork will fetch a high price."};
