#pragma once

#include <string>

const std::string htmlContent2 =
    " </a> <a href=\"/recents\" class=\"ul-recents-link ul-logged-in-show\" id=\"ul-recents-link\"><span "
    "class=\"ul-recents-icon\"><svg width=\"18px\" height=\"18px\" viewbox=\"0 0 18 18\" version=\"1.1\" "
    "xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"><g id=\"Recents\" "
    "stroke=\"none\" stroke-width=\"1\" fill=\"none\" fill-rule=\"evenodd\"><path d=\"M9,0 C6.5179692,0 "
    "4.2714846,1.0125 2.64375,2.64375 L0.9,0.9 L0.9,5.4 L5.4,5.4 L3.909375,3.909375 C5.2136721,2.6050779 "
    "7.0136721,1.8 9,1.8 C12.9691404,1.8 16.2,5.0308596 16.2,9 C16.2,12.9691404 12.9691404,16.2 9,16.2 "
    "C5.0308596,16.2 1.8,12.9691404 1.8,9 C1.8,8.6941404 1.8175779,8.3953125 1.85625,8.1 L0.05625,8.1 "
    "C0.028125,8.3953125 0,8.6941404 0,9 C0,13.9640625 4.0359375,18 9,18 C13.9640625,18 18,13.9640625 18,9 "
    "C18,4.0359375 13.9640625,0 9,0 Z M8,5 L8,9.97841727 L10.8,13 L12,11.705036 L9.70666667,9.23021583 "
    "L9.70666667,5 L8,5 Z\" id=\"Shape\" fill=\"#ffffff\" fill-rule=\"nonzero\"></path></g></svg></span>view "
    "recents</a></ul></div> <div class=\"menu-mob-underlay\" id=\"menu-mob-underlay\"></div> <div "
    "class=\"abl mw-ad-slot-top abl-m320-t728-d728\"><div id=\"mw-ad-slot-top\"></div></div> "
    "<script>window.mwHeapEvents['Definition - Function Label']=\"noun\";window.mwHeapEvents['Definition - "
    "Has Homograph']=\"true\";window.mwHeapEvents['Definition - Number of "
    "Words']=326;window.mwHeapEvents['Definition - Number of Senses']=14;</script> <div "
    "id=\"definition-wrapper\" class=\"container\" data-word-click=\"enabled\"><div class=\"row\"><div "
    "class=\"left-content col-lg-7 col-xl-8\" id=\"left-content\"><span href=\"#\" data-hom=\"1\" "
    "class=\"anchor-name ga-track-hom\" id=\"h1-anchor\"></span> <div class=\"row entry-header\"><div "
    "class=\"col-12\"><h1 class=\"hword\">fish</h1> <span class=\"fl\"><a class=\"important-blue-link\" "
    "href=\"/dictionary/noun\">noun</a></span><span class=\"lbs\">, <span class=\"lb\">often "
    "attributive</span></span></div> <div class=\"col-12 save-to-list\"><a id=\"save-to-list-link\" "
    "href=\"/saved-words\" data-ref=\"dictionary\" data-word=\"fish\"><span class=\"ul-add-icon "
    "ul-icon\"><svg class=\"ul-word-list-icon\" width=\"14px\" height=\"19px\" viewbox=\"0 0 14 19\" "
    "version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"><g "
    "id=\"WordList\" stroke=\"none\" stroke-width=\"1\" fill=\"none\" fill-rule=\"evenodd\"><rect "
    "id=\"RectFill\" class=\"rect-fill\" x=\"1\" y=\"1\" width=\"12\" height=\"9\" r=\"0\" rx=\"0\" ry=\"0\" "
    "stroke=\"none\"></rect> <polygon id=\"Path-10\" fill=\"#97bece\" points=\"1 8 13 8 13 17 7 12.6775391 1 "
    "17\"></polygon> <polygon id=\"Path-11\" stroke=\"#fff\" stroke-width=\"1.5\" points=\"1 1 13 1 13 17 "
    "6.98357563 12.2587174 1 17\"></polygon></g></svg></span> <span id=\"save-to-list-txt\">Save "
    "Word</span></a></div></div> <div class=\"ul-must-login-def\"><transition name=\"fade\"><div "
    "class=\"ul-confirm-dialog\" id=\"ul-must-login\"><div class=\"ul-confirm-dialog-window\"><p>To save "
    "this word, you'll need to log in. <div class=\"actions\"><a class=\"ul-button ul-button-secondary "
    "hoverable\" href=\"/login\"><div class=\"ul-action-text\">Log In <img width=\"18\" height=\"18\" "
    "class=\"svg\" "
    "src=\"https://merriam-webster.com/assets/mw/dist/compiled/images/svg/double-arrows-white.svg\" alt=\"\" "
    "aria-hidden=\"true\"></div></a></div> <div class=\"mw__arrow\" "
    "x-arrow=\"\"></div></div></div></transition></div> <div class=\"row entry-attr\"><div "
    "class=\"col\"><span class=\"prs\"><span class=\"first-slash\">\\</span><span class=\"pr\"> ˈfish</span> "
    "<a class=\"play-pron hw-play-pron\" data-lang=\"en_us\" data-file=\"fish0001\" data-dir=\"f\" "
    "href=\"https://www.merriam-webster.com/dictionary/"
    "fish?pronunciation&lang=en_us&dir=f&amp;file=fish0001\" "
    "data-url=\"https://www.merriam-webster.com/dictionary/"
    "fish?pronunciation&lang=en_us&dir=f&amp;file=fish0001\" data-title=\"How to pronounce fish (audio)\" "
    "title=\"How to pronounce fish (audio)\"><img class=\"svg\" "
    "src=\"https://merriam-webster.com/assets/mw/dist/compiled/images/svg/audio.svg\" alt=\"How to pronounce "
    "fish (audio)\"></a> <span class=\"last-slash\">\\</span></span></div></div> <div class=\"row "
    "headword-row\"><div class=\"col\"><span class=\"vg-ins\"><span class=\"il plural\"> "
    "plural&#32;</span><span class=\"if\">fish</span><span class=\"il or\"> or&#32;</span><span "
    "class=\"if\">fishes</span></span></div></div> <div id=\"dictionary-entry-1\"><div class=\"row "
    "vg-header\"><div class=\"col\"><h2>Definition of <em>fish</em></h2><p "
    "class=\"entryNumbers\">&nbsp;(Entry 1 of 3)</div></div> <div class=\"vg\"><div class=\"sb has-num "
    "has-let\"><span class=\"sb-0\"><div class=\"sense has-sn\"><span class=\"sn sense-1 a\"><span "
    "class=\"num\">1</span><span class=\"letter\">a</span></span> <span class=\"dt \"><span "
    "class=\"dtText\"><strong class=\"mw_t_bc\">: </strong>an aquatic animal                                 "
    "     \n"
    "                <span class=\"uns\"><span class=\"un\"><span class=\"mdash\">&mdash;</span><span "
    "class=\"unText\">usually used in combination<span class=\"vis\"><span class=\"vi\"><span "
    "class=\"ex-sent first-child t no-aq sents\">star<em class=\"mw_t_it\">fish</em></span></span><span "
    "class=\"vi\"><span class=\"ex-sent  t no-aq sents\">cuttle<em "
    "class=\"mw_t_it\">fish</em></span></span></span></span></span></span></span></span></div></span> <span "
    "class=\"sb-1\"><div class=\"sense has-sn\"><span class=\"sn sense-b\"><span "
    "class=\"letter\">b</span></span> <span class=\"dt \"><span class=\"dtText\"><strong class=\"mw_t_bc\">: "
    "</strong>any of numerous cold-blooded strictly aquatic <a href=\"/dictionary/craniate\" "
    "class=\"mw_t_d_link\">craniate</a> vertebrates that include the bony fishes and usually the <a "
    "href=\"/dictionary/cartilaginous fish\" class=\"mw_t_d_link\">cartilaginous</a> and jawless fishes and "
    "that have typically an elongated somewhat spindle-shaped body terminating in a broad caudal (see <a "
    "href=\"/dictionary/caudal\" class=\"mw_t_dxt\"><span class=\"text-uppercase\">caudal</span> <span "
    "class=\"text-lowercase\">sense 2</span></a>) fin, limbs in the form of fins when present at all, and a "
    "2-chambered heart by which blood is sent through <a href=\"/dictionary/thoracic\" "
    "class=\"mw_t_d_link\">thoracic</a> gills to be oxygenated                                      \n"
    "             \n"
    "             <span class=\"ex-sent first-child t no-aq sents\">freshwater <span "
    "class=\"mw_t_wi\">fish</span></span> <span class=\"ex-sent  t no-aq sents\">tropical <span "
    "class=\"mw_t_wi\">fish</span></span></span></span></div></span></div> <div class=\"sb has-num\"><span "
    "class=\"sb-0\"><div class=\"sense has-num-only\"><span class=\"sn sense-2\"><span "
    "class=\"num\">2</span></span> <span class=\"dt \"><span class=\"dtText\"><strong class=\"mw_t_bc\">: "
    "</strong>the flesh of fish used as food                                      \n"
    "             \n"
    "             <span class=\"ex-sent first-child t no-aq sents\">We're having <span "
    "class=\"mw_t_wi\">fish</span> for dinner.</span></span></span></div></span></div> <div class=\"sb "
    "has-num has-let\"><span class=\"sb-0\"><div class=\"sense has-sn\"><span class=\"sn sense-3 a\"><span "
    "class=\"num\">3</span><span class=\"letter\">a</span></span> <span class=\"dt \"><span "
    "class=\"dtText\"><strong class=\"mw_t_bc\">: </strong>a person who is caught or is wanted (as in a "
    "criminal investigation)</span></span></div></span> <span class=\"sb-1\"><div class=\"sense "
    "has-sn\"><span class=\"sn sense-b\"><span class=\"letter\">b</span></span> <span class=\"dt \"><span "
    "class=\"dtText\"><strong class=\"mw_t_bc\">: </strong><a href=\"/dictionary/fellow\" "
    "class=\"mw_t_sx\"><span class=\"text-uppercase\">fellow</span></a>, <a href=\"/dictionary/person\" "
    "class=\"mw_t_sx\"><span class=\"text-uppercase\">person</span></a> <span class=\"ex-sent first-child t "
    "no-aq sents\">an odd <span class=\"mw_t_wi\">fish</span></span></span></span></div></span> <span "
    "class=\"sb-2\"><div class=\"sense has-sn\"><span class=\"sn sense-c\"><span "
    "class=\"letter\">c</span></span> <span class=\"dt \"><span class=\"dtText\"><strong class=\"mw_t_bc\">: "
    "</strong><a href=\"/dictionary/sucker\" class=\"mw_t_sx\"><span class=\"text-uppercase\">sucker</span> "
    "<span class=\"text-lowercase\">sense 5a</span></a> <span class=\"ex-sent first-child t no-aq "
    "sents\">felt sorry for the poor <span "
    "class=\"mw_t_wi\">fish</span></span></span></span></div></span></div> <div class=\"sb has-num "
    "has-let\"><span class=\"sb-0\"><div class=\"sense has-num-only\"><span class=\"sn sense-4\"><span "
    "class=\"num\">4</span></span> <span class=\"dt \"><span class=\"dtText\"><strong class=\"mw_t_bc\">: "
    "</strong>something that resembles a fish: such as</span></span></div></span> <span class=\"sb-1\"><div "
    "class=\"sense has-sn\"><span class=\"sn sense-a\"><span class=\"letter\">a</span></span> <span "
    "class=\"if\">Fish</span><span class=\"il or\"> or&#32;</span><span class=\"if\">Fishes</span><span "
    "class=\"spl plural\"> plural</span> <span class=\"dt hasSdSense\"><span class=\"dtText\"><strong "
    "class=\"mw_t_bc\">: </strong><a href=\"/dictionary/pisces\" class=\"mw_t_sx\"><span "
    "class=\"text-uppercase\">pisces</span> <span class=\"text-lowercase\">sense 1</span></a></span></span> "
    "<span class=\"sdsense\"><span class=\"sd\">also</span> <span class=\"dtText\"><strong "
    "class=\"mw_t_bc\">: </strong><a href=\"/dictionary/pisces\" class=\"mw_t_sx\"><span "
    "class=\"text-uppercase\">pisces</span> <span class=\"text-lowercase\">sense "
    "2a</span></a></span></span></div></span> <span class=\"sb-2\"><div class=\"sense has-sn\"><span "
    "class=\"sn sense-b\"><span class=\"letter\">b</span></span> <span class=\"dt \"><span "
    "class=\"dtText\"><strong class=\"mw_t_bc\">: </strong><a href=\"/dictionary/torpedo\" "
    "class=\"mw_t_sx\"><span class=\"text-uppercase\">torpedo</span> <span class=\"text-lowercase\">sense "
    "1b</span></a> <span class=\"ex-sent first-child t no-aq sents\">The submarine's <span "
    "class=\"mw_t_wi\">fish</span> hit the freighter.</span></span></span></div></span></div></div> <div "
    "class=\"dro\"><span id=\"fish-out-of-water-anchor\" class=\"drp\">fish out of water</span> <div "
    "class=\"vg\"><div class=\"sb no-sn\"><span class=\"sb-0\"><div class=\"sense no-subnum\"><span "
    "class=\"dt \"><span class=\"dtText\"><strong class=\"mw_t_bc\">: </strong>a person who is in an "
    "unnatural or uncomfortable sphere or situation                                      \n"
    "             \n"
    "             <span class=\"ex-sent first-child t no-aq sents\">The country boy felt like a <em "
    "class=\"mw_t_it\">fish out of water</em> in the big city.</span></span></span></div></span></div></div> "
    "<span id=\"fish-to-fry-anchor\" class=\"drp\">fish to fry</span> <div class=\"vg\"><div class=\"sb "
    "no-sn\"><span class=\"sb-0\"><div class=\"sense no-subnum\"><span class=\"dt \"><span "
    "class=\"dtText\"><strong class=\"mw_t_bc\">: </strong>concerns or interests to pursue                   "
    "                   \n"
    "                <span class=\"uns\"><span class=\"un\"><span class=\"mdash\">&mdash;</span><span "
    "class=\"unText\">usually used with <em class=\"mw_t_it\">other</em><span class=\"vis\"><span "
    "class=\"vi\"><span class=\"ex-sent first-child t no-aq sents\">can't deal with that problem now; we've "
    "got other <em class=\"mw_t_it\">fish to fry</em> right "
    "now</span></span></span></span></span></span></span></span></div></span></div></div> <span "
    "id=\"neither-fish-nor-fowl-anchor\" class=\"drp\">neither fish nor fowl</span> <div class=\"vg\"><div "
    "class=\"sb no-sn\"><span class=\"sb-0\"><div class=\"sense no-subnum\"><span class=\"dt \"><span "
    "class=\"dtText\"><strong class=\"mw_t_bc\">: </strong>one that does not belong to a particular class or "
    "category                                      \n"
    "             \n"
    "             <span class=\"ex-sent first-child t no-aq sents\">The movie is <em "
    "class=\"mw_t_it\">neither fish nor fowl</em>—it's not really a comedy, but it's too light-hearted to be "
    "called a drama.</span></span></span></div></span></div></div></div></div> <span href=\"#\" "
    "data-hom=\"2\" class=\"anchor-name anchor-spacer ga-track-hom\" id=\"h2-anchor\"></span> <div "
    "class=\"row entry-header\"><div class=\"col-12\"><p class=\"hword\">fish</p> <span class=\"fl\"><a "
    "class=\"important-blue-link\" href=\"/dictionary/verb\">verb</a></span></div></div> <div class=\"row "
    "headword-row\"><div class=\"col\"><span class=\"vg-ins\"><span class=\"if\">fished</span><span "
    "class=\"sep-semicolon\">; </span><span class=\"if\">fishing</span><span class=\"sep-semicolon\">; "
    "</span><span class=\"if\">fishes</span></span></div></div> <div id=\"dictionary-entry-2\"><div "
    "class=\"row vg-header\"><div class=\"col\"><p class=\"hword2\">Definition of <em>fish</em>&nbsp;(Entry "
    "2 of 3)</div></div> <div class=\"vg\"><p class=\"vd firstVd\"><a class=\"important-blue-link\" "
    "href=\"/dictionary/intransitive\">intransitive verb</a> <div class=\"sb has-num\"><span "
    "class=\"sb-0\"><div class=\"sense has-num-only\"><span class=\"sn sense-1\"><span "
    "class=\"num\">1</span></span> <span class=\"dt \"><span class=\"dtText\"><strong class=\"mw_t_bc\">: "
    "</strong>to attempt to catch fish</span></span></div></span></div> <div class=\"sb has-num\"><span "
    "class=\"sb-0\"><div class=\"sense has-num-only\"><span class=\"sn sense-2\"><span "
    "class=\"num\">2</span></span> <span class=\"dt \"><span class=\"dtText\"><strong class=\"mw_t_bc\">: "
    "</strong>to seek something by roundabout means                                      \n"
    "             \n"
    "             <span class=\"ex-sent first-child t no-aq sents\"><span class=\"mw_t_sp\"><span "
    "class=\"mw_t_wi\">fishing</span> for a compliment</span></span></span></span></div></span></div> <div "
    "class=\"sb has-num has-let\"><span class=\"sb-0\"><div class=\"sense has-sn\"><span class=\"sn sense-3 "
    "a\"><span class=\"num\">3</span><span class=\"letter\">a</span></span> <span class=\"dt \"><span "
    "class=\"dtText\"><strong class=\"mw_t_bc\">: </strong>to search for something underwater                "
    "                      \n"
    "             \n"
    "             <span class=\"ex-sent first-child t no-aq sents\"><span class=\"mw_t_sp\"><span "
    "class=\"mw_t_wi\">fish</span> for pearls</span></span></span></span></div></span> <span "
    "class=\"sb-1\"><div class=\"sense has-sn\"><span class=\"sn sense-b\"><span "
    "class=\"letter\">b</span></span> <span class=\"dt \"><span class=\"dtText\"><strong class=\"mw_t_bc\">: "
    "</strong>to engage in a search by groping or feeling                                      \n"
    "             \n"
    "             <span class=\"ex-sent first-child t no-aq sents\"><span class=\"mw_t_sp\"><span "
    "class=\"mw_t_wi\">fishing</span> around in her purse for her "
    "keys</span></span></span></span></div></span></div></div> <div class=\"vg\"><p class=\"vd\"><a "
    "class=\"important-blue-link\" href=\"/dictionary/transitive\">transitive verb</a> <div class=\"sb "
    "has-num has-let\"><span class=\"sb-0\"><div class=\"sense has-sn\"><span class=\"sn sense-1 a\"><span "
    "class=\"num\">1</span><span class=\"letter\">a</span></span> <span class=\"dt \"><span "
    "class=\"dtText\"><strong class=\"mw_t_bc\">: </strong>to try to catch fish "
    "in</span></span></div></span> <span class=\"sb-1\"><div class=\"sense has-sn\"><span class=\"sn "
    "sense-b\"><span class=\"letter\">b</span></span> <span class=\"dt \"><span class=\"dtText\"><strong "
    "class=\"mw_t_bc\">: </strong>to fish with <strong class=\"mw_t_bc\">: </strong>use (something, such as "
    "a boat, a net, or bait) in <a href=\"/dictionary/fishing\" "
    "class=\"mw_t_a_link\">fishing</a></span></span></div></span></div> <div class=\"sb has-num "
    "has-let\"><span class=\"sb-0\"><div class=\"sense has-sn\"><span class=\"sn sense-2 a\"><span "
    "class=\"num\">2</span><span class=\"letter\">a</span></span> <span class=\"dt \"><span "
    "class=\"dtText\"><strong class=\"mw_t_bc\">: </strong>to go fishing for                                 "
    "     \n"
    "             \n"
    "             <span class=\"ex-sent first-child t no-aq sents\"><span class=\"mw_t_sp\"><span "
    "class=\"mw_t_wi\">fish</span> salmon</span></span></span></span></div></span> <span class=\"sb-1\"><div "
    "class=\"sense has-sn\"><span class=\"sn sense-b\"><span class=\"letter\">b</span></span> <span "
    "class=\"dt \"><span class=\"dtText\"><strong class=\"mw_t_bc\">: </strong>to pull or draw as if fishing "
    "                                     \n"
    "             \n"
    "             <span class=\"ex-sent first-child t no-aq sents\"><span class=\"mw_t_sp\"><span "
    "class=\"mw_t_wi\">fished</span> the ball from under the car</span></span> <span class=\"ex-sent  t "
    "no-aq sents\"><span class=\"mw_t_sp\"><span class=\"mw_t_wi\">fish</span> wires through a "
    "conduit</span></span></span></span></div></span></div></div> <div class=\"dro\"><span "
    "id=\"fish-or-cut-bait-anchor\" class=\"drp\">fish or cut bait</span> <div class=\"vg\"><div class=\"sb "
    "no-sn\"><span class=\"sb-0\"><div class=\"sense no-subnum\"><span class=\"dt \"><span "
    "class=\"dtText\"><strong class=\"mw_t_bc\">: </strong>to make a choice between "
    "alternatives</span></span></div></span></div></div></div></div> <span href=\"#\" data-hom=\"3\" "
    "class=\"anchor-name anchor-spacer\" id=\"b-anchor\"></span> <div class=\"row entry-header\"><div "
    "class=\"col-12\"><p class=\"hword\">Fish</p> <span class=\"fl\">biographical name</span></div></div> "
    "<div class=\"row entry-attr\"><div class=\"col\"><span class=\"prs\"><span "
    "class=\"first-slash\">\\</span><span class=\"pr\"> ˈfish</span> <a class=\"play-pron hw-play-pron\" "
    "data-lang=\"en_us\" data-file=\"bixfis03\" data-dir=\"bix\" "
    "href=\"https://www.merriam-webster.com/dictionary/"
    "Fish?pronunciation&lang=en_us&dir=bix&amp;file=bixfis03\" "
    "data-url=\"https://www.merriam-webster.com/dictionary/"
    "Fish?pronunciation&lang=en_us&dir=bix&amp;file=bixfis03\" data-title=\"How to pronounce Fish (audio)\" "
    "title=\"How to pronounce Fish (audio)\"><img class=\"svg\" "
    "src=\"https://merriam-webster.com/assets/mw/dist/compiled/images/svg/audio.svg\" alt=\"How to pronounce "
    "Fish (audio)\"></a> <span class=\"last-slash\">\\</span></span></div></div> <div "
    "id=\"dictionary-entry-3\"><div class=\"row vg-header\"><div class=\"col\"><p "
    "class=\"hword2\">Definition of <em>Fish</em>&nbsp;(Entry 3 of 3)</div></div> <div class=\"vg\"><div "
    "class=\"sb no-sn\"><span class=\"sb-0\"><div class=\"sense no-subnum\"><span class=\"dt \"><span "
    "class=\"dtText\">Hamilton 1808–1893 American statesman</span></span></div></span></div></div></div> "
    "<div id=\"art-anchor\" class=\"widget illustrations\"><h2>Illustration of <em>fish</em></h2> <img "
    "alt=\"Illustration of fish\" class=\"lazyload\" "
    "data-src=\"https://merriam-webster.com/assets/mw/static/art/dict/fish.gif\"> <p "
    "class=\"function-label\">Noun <p class=\"caption\">fish 1b: <em class=\"mw_t_it\">1</em> mandible, <em "
    "class=\"mw_t_it\">2</em> nasal opening, <em class=\"mw_t_it\">3</em> eye, <em class=\"mw_t_it\">4</em> "
    "cheek, <em class=\"mw_t_it\">5</em> operculum, <em class=\"mw_t_it\">6</em> dorsal fins, <em "
    "class=\"mw_t_it\">7</em> lateral line, <em class=\"mw_t_it\">8</em> caudal fin, <em "
    "class=\"mw_t_it\">9</em> scales, <em class=\"mw_t_it\">10</em> anal fin, <em class=\"mw_t_it\">11</em> "
    "anus, <em class=\"mw_t_it\">12</em> pectoral fin, <em class=\"mw_t_it\">13</em> pelvic fin, <em "
    "class=\"mw_t_it\">14</em> maxilla, <em class=\"mw_t_it\">15</em> premaxilla, <em "
    "class=\"mw_t_it\">16</em> upper jaw <p>In the meaning defined <a href=\"#h1\">above</a></div> "
    "<script>window.mwHeapEvents['Definition - Has Jumplinks']=\"true\";</script> <div "
    "class=\"wgt-incentive-anchors\"><div class=\"anchor-list\"><a href=\"#other-words\" "
    "data-tracking-action=\"Scroll Anchor Link Click\" data-tracking-category=\"Engagement - Definition\" "
    "data-tracking-label=\"UROs: fish\" data-link=\".uro-module-anchor\" data-hash=\"other-words\"><svg "
    "width=\"22px\" height=\"26px\" viewbox=\"0 0 22 26\" version=\"1.1\" "
    "xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"><g "
    "class=\"Jumplink_Arrow\" stroke=\"none\" stroke-width=\"1\" fill=\"none\" fill-rule=\"evenodd\"><g "
    "class=\"Arrow\" fill=\"#97bece\" fill-rule=\"nonzero\"><path class=\"logo Combined-Shape\" "
    "d=\"M13,19.5635256 L18.668743,14.5074335 C19.4930647,13.7722005 20.7573336,13.8444213 "
    "21.4925665,14.668743 C22.2277995,15.4930647 22.1555787,16.7573336 21.331257,17.4925665 "
    "L12.3618903,25.4925665 C11.6052562,26.1674271 10.46334,26.1693571 9.7044291,25.4970579 "
    "L0.673795825,17.4970579 C-0.153006447,16.7646156 -0.229500284,15.5005981 0.502942057,14.6737958 "
    "C1.2353844,13.8469936 2.4994019,13.7704997 3.32620418,14.5029421 L9,19.5292082 L9,2 C9,0.8954305 "
    "9.8954305,0 11,0 C12.1045695,0 13,0.8954305 13,2 L13,19.5635256 Z\"></path></g></g></svg>\n"
    "            Other Words from <em>fish</em></a> <a href=\"#synonyms\" data-tracking-action=\"Scroll "
    "Anchor Link Click\" data-tracking-category=\"Engagement - Definition\" data-tracking-label=\"Synonym "
    "Antonym Guide: fish\" data-link=\".thesaurus-synonyms-module-anchor\" data-hash=\"synonyms\"><svg "
    "width=\"22px\" height=\"26px\" viewbox=\"0 0 22 26\" version=\"1.1\" "
    "xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"><g "
    "class=\"Jumplink_Arrow\" stroke=\"none\" stroke-width=\"1\" fill=\"none\" fill-rule=\"evenodd\"><g "
    "class=\"Arrow\" fill=\"#97bece\" fill-rule=\"nonzero\"><path class=\"logo Combined-Shape\" "
    "d=\"M13,19.5635256 L18.668743,14.5074335 C19.4930647,13.7722005 20.7573336,13.8444213 "
    "21.4925665,14.668743 C22.2277995,15.4930647 22.1555787,16.7573336 21.331257,17.4925665 "
    "L12.3618903,25.4925665 C11.6052562,26.1674271 10.46334,26.1693571 9.7044291,25.4970579 "
    "L0.673795825,17.4970579 C-0.153006447,16.7646156 -0.229500284,15.5005981 0.502942057,14.6737958 "
    "C1.2353844,13.8469936 2.4994019,13.7704997 3.32620418,14.5029421 L9,19.5292082 L9,2 C9,0.8954305 "
    "9.8954305,0 11,0 C12.1045695,0 13,0.8954305 13,2 L13,19.5635256 Z\"></path></g></g></svg>\n"
    "            Synonyms        </a> <a href=\"#examples\" data-tracking-action=\"Scroll Anchor Link "
    "Click\" data-tracking-category=\"Engagement - Definition\" data-tracking-label=\"Examples: fish\" "
    "data-link=\".examples-module-anchor\" data-hash=\"examples\"><svg width=\"22px\" height=\"26px\" "
    "viewbox=\"0 0 22 26\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" "
    "xmlns:xlink=\"http://www.w3.org/1999/xlink\"><g class=\"Jumplink_Arrow\" stroke=\"none\" "
    "stroke-width=\"1\" fill=\"none\" fill-rule=\"evenodd\"><g class=\"Arrow\" fill=\"#97bece\" "
    "fill-rule=\"nonzero\"><path class=\"logo Combined-Shape\" d=\"M13,19.5635256 L18.668743,14.5074335 "
    "C19.4930647,13.7722005 20.7573336,13.8444213 21.4925665,14.668743 C22.2277995,15.4930647 "
    "22.1555787,16.7573336 21.331257,17.4925665 L12.3618903,25.4925665 C11.6052562,26.1674271 "
    "10.46334,26.1693571 9.7044291,25.4970579 L0.673795825,17.4970579 C-0.153006447,16.7646156 "
    "-0.229500284,15.5005981 0.502942057,14.6737958 C1.2353844,13.8469936 2.4994019,13.7704997 "
    "3.32620418,14.5029421 L9,19.5292082 L9,2 C9,0.8954305 9.8954305,0 11,0 C12.1045695,0 13,0.8954305 13,2 "
    "L13,19.5635256 Z\"></path></g></g></svg>\n"
    "            More Example Sentences          </a> <a href=\"#learn-more\" data-tracking-action=\"Scroll "
    "Anchor Link Click\" data-tracking-category=\"Engagement - Definition\" data-tracking-label=\"Learn "
    "More: fish\" data-link=\".learn-more-module-anchor\" data-hash=\"learn-more\"><svg width=\"22px\" "
    "height=\"26px\" viewbox=\"0 0 22 26\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" "
    "xmlns:xlink=\"http://www.w3.org/1999/xlink\"><g class=\"Jumplink_Arrow\" stroke=\"none\" "
    "stroke-width=\"1\" fill=\"none\" fill-rule=\"evenodd\"><g class=\"Arrow\" fill=\"#97bece\" "
    "fill-rule=\"nonzero\"><path class=\"logo Combined-Shape\" d=\"M13,19.5635256 L18.668743,14.5074335 "
    "C19.4930647,13.7722005 20.7573336,13.8444213 21.4925665,14.668743 C22.2277995,15.4930647 "
    "22.1555787,16.7573336 21.331257,17.4925665 L12.3618903,25.4925665 C11.6052562,26.1674271 "
    "10.46334,26.1693571 9.7044291,25.4970579 L0.673795825,17.4970579 C-0.153006447,16.7646156 "
    "-0.229500284,15.5005981 0.502942057,14.6737958 C1.2353844,13.8469936 2.4994019,13.7704997 "
    "3.32620418,14.5029421 L9,19.5292082 L9,2 C9,0.8954305 9.8954305,0 11,0 C12.1045695,0 13,0.8954305 13,2 "
    "L13,19.5635256 Z\"></path></g></g></svg>\n"
    "            Learn More about <em>fish</em></a></div></div> <span id=\"anchor-seporator\"></span> <div "
    "class=\"d-block d-lg-none d-xl-none ads\"><p class=\"text-center disclaimer font-italic\">Keep "
    "scrolling for more <div class=\"light-break above-ads\"></div> <div class=\"abl mw-ad-slot-top "
    "abl-m300-t728-d728 mw-ad-slot-content\"></div> <div class=\"light-break below-ads\"></div></div> "
    "<script>window.mwHeapEvents['Has Other Words From']=\"true\";</script> <div id=\"other-words-anchor\" "
    "class=\"widget uros uro-module-anchor\"><h2>Other Words from <em>fish</em></h2> <p "
    "class=\"function-label\">Noun <div class=\"uro\"><span class=\"ure\">fishless</span> <span "
    "class=\"first-slash\">\\</span> <span class=\"prt-a\"><span class=\"mw\">ˈfish-&#8203;ləs    </span> <a "
    "class=\"play-pron\" data-lang=\"en_us\" data-file=\"fish0002\" data-dir=\"f\" "
    "href=\"https://www.merriam-webster.com/dictionary/"
    "fishless?pronunciation&lang=en_us&dir=f&amp;file=fish0002\" data-title=\"How to pronounce fishless "
    "(audio)\" title=\"How to pronounce fishless (audio)\"><img class=\"svg\" alt=\"How to pronounce "
    "fishless (audio)\" "
    "src=\"https://merriam-webster.com/assets/mw/dist/compiled/images/svg/audio.svg\"></a></span> <span "
    "class=\"last-slash\">\\</span> <span class=\"fl\">adjective</span></div> <div class=\"uro\"><span "
    "class=\"ure\">fishlike</span> <span class=\"first-slash\">\\</span> <span class=\"prt-a\"><span "
    "class=\"mw\">ˈfish-&#8203;ˌlīk    </span> <a class=\"play-pron\" data-lang=\"en_us\" "
    "data-file=\"fish0003\" data-dir=\"f\" "
    "href=\"https://www.merriam-webster.com/dictionary/"
    "fishlike?pronunciation&lang=en_us&dir=f&amp;file=fish0003\" data-title=\"How to pronounce fishlike "
    "(audio)\" title=\"How to pronounce fishlike (audio)\"><img class=\"svg\" alt=\"How to pronounce "
    "fishlike (audio)\" "
    "src=\"https://merriam-webster.com/assets/mw/dist/compiled/images/svg/audio.svg\"></a></span> <span "
    "class=\"last-slash\">\\</span> <span class=\"fl\">adjective</span></div> <p "
    "class=\"function-label\">Verb <div class=\"uro\"><span class=\"ure\">fishability</span> <span "
    "class=\"first-slash\">\\</span> <span class=\"prt-a\"><span "
    "class=\"mw\">ˌfi-&#8203;shə-&#8203;ˈbi-&#8203;lə-&#8203;tē    </span> <a class=\"play-pron\" "
    "data-lang=\"en_us\" data-file=\"fish0004\" data-dir=\"f\" "
    "href=\"https://www.merriam-webster.com/dictionary/"
    "fishability?pronunciation&lang=en_us&dir=f&amp;file=fish0004\" data-title=\"How to pronounce "
    "fishability (audio)\" title=\"How to pronounce fishability (audio)\"><img class=\"svg\" alt=\"How to "
    "pronounce fishability (audio)\" "
    "src=\"https://merriam-webster.com/assets/mw/dist/compiled/images/svg/audio.svg\"></a></span> <span "
    "class=\"last-slash\">\\</span> <span class=\"fl\">noun</span></div> <div class=\"uro\"><span "
    "class=\"ure\">fishable</span> <span class=\"first-slash\">\\</span> <span class=\"prt-a\"><span "
    "class=\"mw\">ˈfi-&#8203;shə-&#8203;bəl    </span> <a class=\"play-pron\" data-lang=\"en_us\" "
    "data-file=\"fish0005\" data-dir=\"f\" "
    "href=\"https://www.merriam-webster.com/dictionary/"
    "fishable?pronunciation&lang=en_us&dir=f&amp;file=fish0005\" data-title=\"How to pronounce fishable "
    "(audio)\" title=\"How to pronounce fishable (audio)\"><img class=\"svg\" alt=\"How to pronounce "
    "fishable (audio)\" "
    "src=\"https://merriam-webster.com/assets/mw/dist/compiled/images/svg/audio.svg\"></a></span> <span "
    "class=\"last-slash\">\\</span> <span class=\"fl\">adjective</span></div></div> <div "
    "id=\"synonyms-anchor\" class=\"widget synonyms_list thesaurus-synonyms-module-anchor\"><h2>Synonyms for "
    "<em>fish</em></h2> <p class=\"function-label\">Synonyms: Noun <ul class=\"mw-list\"><li><a "
    "href=\"/dictionary/baby\">baby</a>, <li><a href=\"/dictionary/being\">being</a>, <li><a "
    "href=\"/dictionary/bird\">bird</a>, <li><a href=\"/dictionary/bod\">bod</a><li>\n"
    "            [<span class=\"wsls\">British</span>], <li><a href=\"/dictionary/body\">body</a>, <li><a "
    "href=\"/dictionary/character\">character</a>, <li><a href=\"/dictionary/cookie\">cookie</a><li><span "
    "class=\"wvrs\"> (<span class=\"wvl\">or</span>&#32;<span class=\"wva\"><a "
    "href=\"/dictionary/cooky\">cooky</a></span>)</span>, <li><a href=\"/dictionary/creature\">creature</a>, "
    "<li><a href=\"/dictionary/customer\">customer</a>, <li><a href=\"/dictionary/devil\">devil</a>, <li><a "
    "href=\"/dictionary/duck\">duck</a>, <li><a href=\"/dictionary/egg\">egg</a>, <li><a "
    "href=\"/dictionary/face\">face</a>, <li><a href=\"/dictionary/guy\">guy</a>, <li><a "
    "href=\"/dictionary/head\">head</a>, <li><a href=\"/dictionary/human\">human</a>, <li><a "
    "href=\"/dictionary/human%20being\">human being</a>, <li><a "
    "href=\"/dictionary/individual\">individual</a>, <li><a href=\"/dictionary/life\">life</a>, <li><a "
    "href=\"/dictionary/man\">man</a>, <li><a href=\"/dictionary/mortal\">mortal</a>, <li><a "
    "href=\"/dictionary/party\">party</a>, <li><a href=\"/dictionary/person\">person</a>, <li><a "
    "href=\"/dictionary/personage\">personage</a>, <li><a href=\"/dictionary/scout\">scout</a>, <li><a "
    "href=\"/dictionary/slob\">slob</a>, <li><a href=\"/dictionary/sort\">sort</a>, <li><a "
    "href=\"/dictionary/soul\">soul</a>, <li><a href=\"/dictionary/specimen\">specimen</a>, <li><a "
    "href=\"/dictionary/stiff\">stiff</a>, <li><a href=\"/dictionary/thing\">thing</a>, <li><a "
    "class=\"syn-last\" href=\"/dictionary/wight\">wight</a></ul> <p class=\"function-label\">Synonyms: Verb "
    "<ul class=\"mw-list\"><li><a href=\"/dictionary/feel\">feel</a>, <li><a "
    "href=\"/dictionary/fumble\">fumble</a>, <li><a href=\"/dictionary/grope\">grope</a>, <li><a "
    "class=\"syn-last\" href=\"/dictionary/scrabble\">scrabble</a></ul> <a class=\"widget-button thesaurus\" "
    "href=\"/thesaurus/fish\">Visit the Thesaurus for More&nbsp;<img class=\"svg double-arrows\" "
    "src=\"https://merriam-webster.com/assets/mw/dist/compiled/images/svg/double-arrows-transparent.svg\"></"
    "a></div> <script>window.mwHeapEvents['Definition - Has Synonyms']=\"true\";</script> <div "
    "id=\"examples-anchor\" class=\"widget example_sentences examples-module-anchor\"><h2>Examples of "
    "<em>fish</em> in a Sentence</h2> <script>window.mwHeapEvents['Definition - Has Example "
    "Sentences']=\"true\";</script> <div class=\"in-sentences\"><span class=\"ex-header "
    "function-label\">Noun</span> <span class=\"ex-sent  t no-aq sents\">\n"
    "         \n"
    "                        We're having <em class=\"mw_t_it\">fish</em> for dinner.    </span> <span "
    "class=\"ex-sent  t no-aq sents\">\n"
    "         \n"
    "                        he's rather an odd <em class=\"mw_t_it\">fish</em></span> <span "
    "class=\"ex-header function-label\">Verb</span> <span class=\"ex-sent  t no-aq sents\">\n"
    "         \n"
    "                        We spent the afternoon <em class=\"mw_t_it\">fishing</em> for trout.    </span> "
    "<span class=\"ex-sent  t no-aq sents\">\n"
    "         \n"
    "                        They <em class=\"mw_t_it\">fished</em> the stream all morning.    </span> <span "
    "class=\"ex-sent  t no-aq sents\">\n"
    "         \n"
    "                        She was <em class=\"mw_t_it\">fishing</em> around in her purse for her keys.    "
    "</span></div> <span id=\"in-sentences\" class=\"widget-button show-expand\" href=\"#\"><span "
    "class=\"see-text\">See More</span><img class=\"svg more\" "
    "src=\"https://merriam-webster.com/assets/mw/dist/compiled/images/svg/show-more.svg\"><img class=\"svg "
    "less\" src=\"https://merriam-webster.com/assets/mw/dist/compiled/images/svg/show-less.svg\"></span> "
    "<div id=\"example-hr\"></div> <script>window.mwHeapEvents['Definition - Has "
    "Henhouse']=\"true\";</script> <div class=\"on-web\"><span class=\"ex-header function-label\">Recent "
    "Examples on the Web: Noun</span> <span class=\"ex-sent sents\" data-example-id=\"7365522\"><span "
    "class=\"t has-aq\">Over the past half century, overfishing and pollution killed off sheepshead "
    "<em>fish</em>, abalone, and other marine animals along the Los Angeles Coast that either preyed on "
    "purple urchins or competed with them for habitat.</span> <span class=\"aq has-aq\">\n"
    "        \t&mdash;\n"
    "        \t<a rel=\"nofollow noopener\" "
    "href=\"https://www.nationalgeographic.com/science/2020/04/"
    "california-critical-kelp-forests-disappearing-warming-world-can-they-be-saved/\" target=\"_blank\">\n"
    "            Maurice Roper, <em>National Geographic</em>, \"THE BEST OF NATIONAL GEOGRAPHIC DELIVERED TO "
    "YOUR INBOX,\" 30 Apr. 2020        \t</a></span></span> <span class=\"ex-sent sents\" "
    "data-example-id=\"7365523\"><span class=\"t has-aq\">The others reported being able to canoe, ice "
    "<em>fish</em>, and ride a snowmobile.</span> <span class=\"aq has-aq\">\n"
    "        \t&mdash;\n"
    "        \t<a rel=\"nofollow noopener\" "
    "href=\"https://www.statnews.com/2020/04/30/mind-controlled-prosthetic-arm-patients-feel-objects/\" "
    "target=\"_blank\">\n"
    "            Shafaq Zia, <em>STAT</em>, \"Mind-controlled prosthetic arm enables patients to feel the "
    "objects they grip,\" 30 Apr. 2020        \t</a></span></span> <span class=\"ex-sent sents\" "
    "data-example-id=\"7365524\"><span class=\"t has-aq\">The birds feed on surface <em>fish</em>, squid and "
    "other prey -- but have also reportedly swooped down and consumed tons of plastic as a species each year "
    "due to pollution of the oceans.</span> <span class=\"aq has-aq\">\n"
    "        \t&mdash;\n"
    "        \t<a rel=\"nofollow noopener\" "
    "href=\"https://www.foxnews.com/science/"
    "laysan-albatross-courtship-dance-midway-atoll-us-fish-wildlife-video\" target=\"_blank\">\n"
    "            Michael Ruiz, <em>Fox News</em>, \"Video of Laysan albatross 'courtship dance' on Midway "
    "Atoll shared by US Fish & Wildlife,\" 30 Apr. 2020        \t</a></span></span> <span class=\"ex-sent "
    "sents\" data-example-id=\"7365525\"><span class=\"t has-aq\">Fishing Through the Apocalypse by Matthew "
    "L. Miller is light on tips and tactics but full of interesting insights into <em>fish</em>, and trout "
    "in particular.</span> <span class=\"aq has-aq\">\n"
    "        \t&mdash;\n"
    "        \t<a rel=\"nofollow noopener\" "
    "href=\"https://www.outdoorlife.com/story/shop/books-about-trout/\" target=\"_blank\"><em>Outdoor "
    "Life</em>, \"Four essential books all about trout fishing,\" 30 Apr. 2020        \t</a></span></span> "
    "<span class=\"ex-sent sents\" data-example-id=\"7365526\"><span class=\"t has-aq\">Pour lemon and lime "
    "juice over <em>fish</em>, cover, and refrigerate for half an hour.</span> <span class=\"aq has-aq\">\n"
    "        \t&mdash;\n"
    "        \t<a rel=\"nofollow noopener\" "
    "href=\"https://www.essence.com/lifestyle/food-drinks/soulful-caribbean-recipes/\" target=\"_blank\">\n"
    "            Kimberly Wilson, <em>Essence</em>, \"Escape To The Caribbean With These Soulful Recipes,\" "
    "29 Apr. 2020        \t</a></span></span> <span class=\"ex-sent sents\" "
    "data-example-id=\"7365527\"><span class=\"t has-aq\">Most fishing rods break during transport or "
    "handling (not when fighting a big <em>fish</em>, as romantic as that may seem), and considering that "
    "the rod will be bouncing around in your trunk or behind the seat, that’s important.</span> <span "
    "class=\"aq has-aq\">\n"
    "        \t&mdash;\n"
    "        \t<a rel=\"nofollow noopener\" "
    "href=\"https://www.fieldandstream.com/story/outdoor-gear/how-to-choose-travel-fishing-rod/\" "
    "target=\"_blank\">\n"
    "            The Editors, <em>Field & Stream</em>, \"How to Choose a Travel Fishing Rod,\" 29 Apr. 2020  "
    "      \t</a></span></span> <span class=\"ex-sent sents\" data-example-id=\"7365528\"><span class=\"t "
    "has-aq\">Sunday Supper Sandwiches Known today as a tuna melt, the retro recipe combines one 6-ounce can "
    "tuna <em>fish</em>, 2 Tbsp.</span> <span class=\"aq has-aq\">\n"
    "        \t&mdash;\n"
    "        \t<a rel=\"nofollow noopener\" href=\"https://www.bhg.com/recipes/classic-bhg-recipes/\" "
    "target=\"_blank\">\n"
    "            Katlyn Moncada, <em>Better Homes & Gardens</em>, \"Recipes and Tips from Our 1943 Edition "
    "of New Cook Book That Are Totally Relevant Today,\" 28 Apr. 2020        \t</a></span></span> <span "
    "class=\"ex-sent sents\" data-example-id=\"7365529\"><span class=\"t has-aq\">Wilson said the "
    "<em>fish</em>, measuring in at 35 inches long, was the biggest one his son had ever caught.</span> "
    "<span class=\"aq has-aq\">\n"
    "        \t&mdash;\n"
    "        \t<a rel=\"nofollow noopener\" "
    "href=\"http://www.cbsnews.com/news/11-year-old-colorado-boy-catches-trout-the-size-of-a-toddler/\" "
    "target=\"_blank\">\n"
    "            Danielle Garrand, <em>CBS News</em>, \"11-year-old Colorado boy catches trout the size of a "
    "toddler,\" 28 Apr. 2020        \t</a></span></span> <span class=\"ex-header function-label\">Recent "
    "Examples on the Web: Verb</span> <span class=\"ex-sent sents\" data-example-id=\"7372940\"><span "
    "class=\"t has-aq\">Boris Johnson’s government plans to reclaim control over British fisheries with a "
    "law allowing the U.K. to decide who can <em>fish </em>in its waters and on what terms.</span> <span "
    "class=\"aq has-aq\">\n"
    "        \t&mdash;\n"
    "        \t<a rel=\"nofollow noopener\" "
    "href=\"https://www.bloomberg.com/news/articles/2020-01-29/"
    "johnson-plans-law-for-control-of-u-k-fisheries-after-brexit\" target=\"_blank\">\n"
    "            Alex Morales, <em>Bloomberg.com</em>, \"Boris Johnson Plans Law for Control of U.K. "
    "Fisheries After Brexit,\" 5 May 2020        \t</a></span></span> <span class=\"ex-sent sents\" "
    "data-example-id=\"7372941\"><span class=\"t has-aq\">Washington state lawsuit targets trollers — Nearly "
    "1,600 trollers who <em>fish </em>for king salmon in Southeast Alaska could be beached this summer over "
    "a lawsuit to protect killer whales — in Puget Sound, Washington.</span> <span class=\"aq has-aq\">\n"
    "        \t&mdash;\n"
    "        \t<a rel=\"nofollow noopener\" "
    "href=\"https://www.adn.com/business-economy/2020/04/28/"
    "strict-new-pandemic-rules-are-in-place-for-alaska-fishermen-and-their-vessels/\" "
    "target=\"_blank\"><em>Anchorage Daily News</em>, \"Strict new pandemic rules are in place for Alaska "
    "fishermen and their vessels,\" 29 Apr. 2020        \t</a></span></span> <span class=\"ex-sent sents\" "
    "data-example-id=\"7372942\"><span class=\"t has-aq\">Those features are especially important for "
    "anglers who are <em>fishing </em>from a kayak or canoe, in which additional weight can hinder speed and "
    "boat control.</span> <span class=\"aq has-aq\">\n"
    "        \t&mdash;\n"
    "        \t<a rel=\"nofollow noopener\" "
    "href=\"https://www.fieldandstream.com/story/outdoor-gear/"
    "things-you-need-before-opening-day-of-fishing-season/\" target=\"_blank\">\n"
    "            The Editors, <em>Field & Stream</em>, \"7 Things You Need Before Opening Day of Fishing "
    "Season,\" 2 Apr. 2020        \t</a></span></span> <span class=\"ex-sent sents\" "
    "data-example-id=\"7372943\"><span class=\"t has-aq\">Residents who <em>fished </em>and bathed in the "
    "Xingu saw their lives take a dramtic turn.</span> <span class=\"aq has-aq\">\n"
    "        \t&mdash;\n"
    "        \t<a rel=\"nofollow noopener\" "
    "href=\"https://www.washingtonpost.com/business/"
    "brazils-amazon-mega-dam-broken-promises-for-distant-power/2019/12/18/"
    "fb55be4e-2153-11ea-b034-de7dc2b5199b_story.html\" target=\"_blank\"><em>Washington Post</em>, "
    "\"Brazil’s Amazon mega-dam: broken promises for distant power,\" 18 Dec. 2019        "
    "\t</a></span></span> <span class=\"ex-sent sents\" data-example-id=\"7268203\"><span class=\"t "
    "has-aq\">The noisemaker that Díaz López used in the study is intended to keep dolphins away from "
    "<em>fishing </em>nets to prevent them from taking the catch from fishermen, and stop them from getting "
    "caught in the net themselves.</span> <span class=\"aq has-aq\">\n"
    "        \t&mdash;\n"
    "        \t<a rel=\"nofollow noopener\" "
    "href=\"https://www.smithsonianmag.com/smart-news/wild-dolphins-have-range-personalities-180974672/\" "
    "target=\"_blank\">\n"
    "            Theresa Machemer, <em>Smithsonian Magazine</em>, \"Wild Dolphins Seem to Have a Range of "
    "Personalities,\" 15 Apr. 2020        \t</a></span></span> <span class=\"ex-sent sents\" "
    "data-example-id=\"7268204\"><span class=\"t has-aq\">Interestingly, Maupin hadn’t planned to be "
    "<em>fishing </em>at O.H. Ivie in the first place.</span> <span class=\"aq has-aq\">\n"
    "        \t&mdash;\n"
    "        \t<a rel=\"nofollow noopener\" "
    "href=\"https://www.dallasnews.com/sports/other-sports/2020/04/11/"
    "no-social-distancing-for-this-bass-cypress-angler-lands-only-sharelunker-reported-after-coronavirus-"
    "outbreak/\" target=\"_blank\">\n"
    "            Matt Williams, <em>Dallas News</em>, \"No social distancing for this bass: Cypress angler "
    "lands only ShareLunker reported after coronavirus outbreak,\" 12 Apr. 2020        \t</a></span></span> "
    "<span class=\"ex-sent sents\" data-example-id=\"7268205\"><span class=\"t has-aq\">Interestingly, the "
    "angler hadn’t planned to be <em>fishing </em>at O.H. Ivie in the first place.</span> <span class=\"aq "
    "has-aq\">\n"
    "        \t&mdash;\n"
    "        \t<a rel=\"nofollow noopener\" "
    "href=\"https://www.expressnews.com/sports/outdoors/article/"
    "Pandemic-concerns-lead-father-son-to-huge-score-15194839.php\" target=\"_blank\">\n"
    "            Matt Williams, <em>ExpressNews.com</em>, \"Pandemic concerns lead father, son to huge "
    "score,\" 11 Apr. 2020        \t</a></span></span> <span class=\"ex-sent sents\" "
    "data-example-id=\"7268206\"><span class=\"t has-aq\">From what country was <em>fishing </em>boat that "
    "was recently sunk in the body of water named in question 7?\n"
    "9.</span> <span class=\"aq has-aq\">\n"
    "        \t&mdash;\n"
    "        \t<a rel=\"nofollow noopener\" "
    "href=\"https://www.cnn.com/2020/04/09/cnn10/ten-content-fri/index.html\" "
    "target=\"_blank\"><em>CNN</em>, \"CNN 10 - April 10, 2020,\" 10 Apr. 2020        \t</a></span></span> "
    "<p class=\"disclaimer\">\n"
    "                                    These example sentences are selected automatically from various "
    "online news sources to reflect current usage of the word 'fish.' Views expressed in the examples do not "
    "represent the opinion of Merriam-Webster or its editors. <a "
    "href=\"/"
    "contact-us?ref=freshexamples&hw=fish&url=https%3A%2F%2Fwww.merriam-webster.com%2Fdictionary%2Ffish\">"
    "Send us feedback</a>.\n"
    "                                </div> <span id=\"on-web\" class=\"widget-button show-expand\" "
    "href=\"#\"><span class=\"see-text\">See More</span><img class=\"svg more\" "
    "src=\"https://merriam-webster.com/assets/mw/dist/compiled/images/svg/show-more.svg\"><img class=\"svg "
    "less\" "
    "src=\"https://merriam-webster.com/assets/mw/dist/compiled/images/svg/show-less.svg\"></span></div> <div "
    "id=\"first-known-anchor\" class=\"widget firstknown-list\"><h2>First Known Use of <em>fish</em></h2> <p "
    "class=\"function-label\">Noun <p class=\"ety-sl\" data-entry-id=\"1\">before the 12th century, in the "
    "meaning defined at <a href=\"#h1\">sense 1a</a> <p class=\"function-label\">Verb <p class=\"ety-sl\" "
    "data-entry-id=\"2\">before the 12th century, in the meaning defined at <a href=\"#h2\">intransitive "
    "sense 1</a></div> <script>window.mwHeapEvents['Definition - Has Etymology']=\"true\";</script> <div "
    "id=\"etymology-anchor\" class=\"widget etymology-list\"><h2>History and Etymology for "
    "<em>fish</em></h2> <p class=\"function-label\">Noun and Verb <p class=\"et\">\n"
    "                Middle English, from Old English <em class=\"mw_t_it\">fisc</em>; akin to Old High "
    "German <em class=\"mw_t_it\">fisc</em> fish, Latin <em class=\"mw_t_it\">piscis</em></div> <div "
    "class=\"d-block d-lg-none d-xl-none ads\"><p class=\"text-center disclaimer font-italic\">Keep "
    "scrolling for more <div class=\"light-break above-ads\"></div> <div class=\"abl mw-ad-slot-top "
    "abl-m320-t728-d728 mw-ad-slot-content\"></div> <div class=\"light-break below-ads\"></div></div> <div "
    "id=\"learn-more-anchor\" class=\"heavy-break learn-more-module-anchor\"></div> <div class=\"widget "
    "learn_more\"><h2 class=\"learn-more-header\">Learn More about <em>fish</em></h2> <div "
    "class=\"light-break\"></div> <div id=\"social-sidebar-container\" class=\"row\"><div "
    "id=\"share-anchor\" class=\"col-md-6\"><p class=\"hword2\">Share <em>fish</em> <div class=\"row\"><div "
    "class=\"col\"><a href=\"#\" class=\"fb share-link\" "
    "data-share-url=\"https://www.merriam-webster.com/dictionary/fish\" "
    "data-share-image=\"https://merriam-webster.com/assets/mw/static/social-media-share/"
    "mw-logo-245x245@1x.png\" data-share-title=\"Definition of FISH\" data-share-description=\"an aquatic "
    "animal —usually used in combination… See the full definition\"><span class=\"aria-text\">Post the "
    "Definition of fish to Facebook</span> <img class=\"svg\" "
    "src=\"https://merriam-webster.com/assets/mw/dist/compiled/images/svg/facebook.svg\" "
    "alt=\"Facebook\"></a> <a href=\"#\" class=\"twitter share-link\" "
    "data-share-url=\"https://www.merriam-webster.com/dictionary/fish\" data-share-text=\"This is the "
    "@MerriamWebster definition of 'fish'\"><span class=\"aria-text\">Share the Definition of fish on "
    "Twitter</span> <img class=\"svg\" "
    "src=\"https://merriam-webster.com/assets/mw/dist/compiled/images/svg/twitter.svg\" "
    "alt=\"Twitter\"></a></div></div></div> <div id=\"time-traveler-anchor\" class=\"col-md-6\"><p "
    "class=\"hword2\">Time Traveler for <em>fish</em></p> <a "
    "href=\"/time-traveler/before-12th-century?src=learn-more-timetraveler\" class=\"time-traveler\"><img "
    "class=\"svg\" src=\"https://merriam-webster.com/assets/mw/dist/compiled/images/svg/time-traveler.svg\" "
    "alt=\"Time Traveler\"></a> <h2 class=\"hword4\">The first known use of <em>fish</em> was \n"
    "                                before the 12th century</h2> <p><a class=\"see-more\" "
    "href=\"/time-traveler/before-12th-century?src=defrecirc-timetraveler-etycard\">See more words from the "
    "same century</a></div></div> <div id=\"browse-dictionary\" class=\"row\"><div "
    "id=\"near-entries-anchor\" class=\"col-md-6\"><h2>Dictionary Entries near <em>fish</em></h2> <p><a "
    "class=\"b-link\" data-ind=\"2\" href=\"/dictionary/Fischer-Tropsch%20process\">Fischer-Tropsch "
    "process</a> <p><a class=\"b-link\" data-ind=\"3\" href=\"/dictionary/fiscus\">fiscus</a> <p><a "
    "class=\"b-link\" data-ind=\"4\" href=\"/dictionary/fisetin\">fisetin</a> <p class=\"active\"><a "
    "class=\"b-link\" data-ind=\"5\" href=\"/dictionary/fish\">fish</a> <p><a class=\"b-link\" "
    "data-ind=\"6\" href=\"/dictionary/Fish\">Fish</a> <p><a class=\"b-link\" data-ind=\"7\" "
    "href=\"/dictionary/fish-and-chips\">fish-and-chips</a> <p><a class=\"b-link\" data-ind=\"8\" "
    "href=\"/dictionary/fish%20ball\">fish ball</a></p> <a class=\"widget-button hoverable see-more-browse\" "
    "href=\"/browse/dictionary/f/19\">See More Nearby Entries&nbsp;<svg xmlns=\"http://www.w3.org/2000/svg\" "
    "xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"18px\" height=\"18px\" viewbox=\"0 0 20 20\" "
    "version=\"1.1\" class=\"svg double-arrows\"><g class=\"Button_DoubleArrow\" stroke=\"none\" "
    "stroke-width=\"1\" fill=\"none\" fill-rule=\"evenodd\"><g class=\"Icon/Button/DoubleArrow\" "
    "transform=\"translate(0.000000, -2.000000)\" fill=\"#ffffff\"><path class=\"outline Oval-2\" d=\"M10,20 "
    "C14.418278,20 18,16.418278 18,12 C18,7.581722 14.418278,4 10,4 C5.581722,4 2,7.581722 2,12 C2,16.418278 "
    "5.581722,20 10,20 Z M10,22 C4.4771525,22 0,17.5228475 0,12 C0,6.4771525 4.4771525,2 10,2 C15.5228475,2 "
    "20,6.4771525 20,12 C20,17.5228475 15.5228475,22 10,22 Z\" fill-rule=\"nonzero\"></path> <path "
    "class=\"logo »\" d=\"M14.5324998,12.5078125 L11.6340623,16.046875 L9.92312479,15.1171875 "
    "L12.0949998,12.3984375 L9.92312479,9.6796875 L11.6340623,8.75 L14.5324998,12.3046875 "
    "L14.5324998,12.5078125 Z M10.5793748,12.5078125 L7.68093729,16.046875 L5.96999979,15.1171875 "
    "L8.14187479,12.3984375 L5.96999979,9.6796875 L7.68093729,8.75 L10.5793748,12.3046875 "
    "L10.5793748,12.5078125 Z\"></path></g></g></svg></a></div> <div id=\"related-phrases-anchor\" "
    "class=\"col-md-6\"><h2>Phrases Related to <em>fish</em></h2> <p><a "
    "href=\"/dictionary/a%20big%20fish%20in%20a%20little%20pond\">a big fish in a little pond</a> <p><a "
    "href=\"/dictionary/a%20big%20fish%20in%20a%20small%20pond\">a big fish in a small pond</a> <p><a "
    "href=\"/dictionary/fish%20for\">fish for</a> <p><a href=\"/dictionary/fish%20for%20compliments\">fish "
    "for compliments</a> <p><a href=\"/dictionary/fish%20in%20the%20sea\">fish in the sea</a> <p><a "
    "href=\"/dictionary/fish%20slice\">fish slice</a> <p><a href=\"/dictionary/ice%20fishing\">ice "
    "fishing</a></div> <div id=\"statistics-anchor\" class=\"col-md-6\"><h2>Statistics for "
    "<em>fish</em></h2> <div class=\"pop-update-wrapper\"><p class=\"function-title\">Last Updated <p "
    "class=\"update-date\">8 May 2020 <div id=\"popularity-block-wrapper\" class=\"hidden\"><p "
    "class=\"function-title\">Look-up Popularity <p id=\"popularity-block\" "
    "class=\"popularity-block\"></div></div></div> <div id=\"cite-anchor\" class=\"col-md-6\"><p "
    "class=\"hword2\">Cite this Entry <p id=\"citationText\">&ldquo;Fish.&rdquo; <em>Merriam-Webster.com "
    "Dictionary</em>, Merriam-Webster, https://www.merriam-webster.com/dictionary/fish. Accessed 15 May. "
    "2020.</p> <select id=\"citations\" class=\"js-example-basic-single\" name=\"citations\" style=\"width: "
    "100%;\" aria-label=\"citations\"><option value=\"\" data-attr=\"\"> <option value=\"mla\" "
    "data-attr=\"&ldquo;Fish.&rdquo; <em>Merriam-Webster.com Dictionary</em>, Merriam-Webster, "
    "https://www.merriam-webster.com/dictionary/fish. Accessed 15 May. 2020.\">MLA <option value=\"chicago\" "
    "data-attr=\"<em>Merriam-Webster.com Dictionary</em>, s.v. &ldquo;fish,&rdquo; accessed May 15, 2020, "
    "https://www.merriam-webster.com/dictionary/fish.\">Chicago <option value=\"apa\" "
    "data-attr=\"Merriam-Webster. (n.d.).  Fish. In <em>Merriam-Webster.com dictionary</em>. Retrieved May "
    "15, 2020, from https://www.merriam-webster.com/dictionary/fish\">APA <option value=\"mw\" "
    "data-attr=\"&ldquo;fish,&rdquo; <em>Merriam-Webster.com Dictionary</em>, "
    "https://www.merriam-webster.com/dictionary/fish. Accessed "
    "5/15/2020.\">Merriam-Webster</select></div></div></div> <div class=\"heavy-break bottom\"></div> <div "
    "class=\"d-block d-lg-none d-xl-none ads\"><p class=\"text-center disclaimer font-italic\">Keep "
    "scrolling for more <div class=\"light-break above-ads\"></div> <div class=\"abl mw-ad-slot-top "
    "abl-m320-t728-d728 mw-ad-slot-content\"></div> <div class=\"light-break below-ads\"></div></div> <div "
    "class=\"heavy-break\"></div> <div class=\"widget more_defs\"><p id=\"more-definitions-anchor\" "
    "class=\"hword2 more-defs-header\">More Definitions for <em>fish</em> <div class=\"light-break\"></div> "
    "<span id=\"learnersdictionary-anchor\"></span> <div id=\"other-entry-1\"><div class=\"row "
    "entry-header\"><div class=\"col\"><p class=\"hword\">fish</p> <span class=\"fl\"><em><a "
    "class=\"important-blue-link\" href=\"/dictionary/noun\">noun</a></em></span></div></div> <div "
    "class=\"row entry-attr\"><div class=\"col\"><span class=\"prs\"><a class=\"play-pron hw-play-pron\" "
    "data-lang=\"en_us\" data-file=\"fish0001\" data-dir=\"f\" "
    "href=\"https://www.merriam-webster.com/dictionary/"
    "Fish?pronunciation&lang=en_us&dir=f&amp;file=fish0001\" "
    "data-url=\"https://www.merriam-webster.com/dictionary/"
    "Fish?pronunciation&lang=en_us&dir=f&amp;file=fish0001\" data-title=\"How to pronounce Fish (audio)\" "
    "title=\"How to pronounce Fish (audio)\"><img class=\"svg\" "
    "src=\"https://merriam-webster.com/assets/mw/dist/compiled/images/svg/audio.svg\" alt=\"How to pronounce "
    "Fish (audio)\"></a></span></div></div> <div class=\"row vg-header\"><div class=\"col\"><h2 "
    "class=\"first-learners\" data-source=\"header-learners\">English Language Learners Definition of "
    "<em>fish</em></h2><p class=\"entryNumbers\">&nbsp;(Entry 1 of 2)</div></div> <div "
    "class=\"learners-def\"><div class=\"vg\"><div class=\"sb no-sn\"><span class=\"sb-0\"><div "
    "class=\"sense no-subnum\"><span class=\"dt \"><span class=\"dtText\"><strong class=\"mw_t_bc\">: "
    "</strong>a cold-blooded animal that lives in water, breathes with gills, and usually has fins and "
    "scales</span></span></div></span></div> <div class=\"sb no-sn\"><span class=\"sb-0\"><div class=\"sense "
    "no-subnum\"><span class=\"dt \"><span class=\"dtText\"><strong class=\"mw_t_bc\">: </strong>the meat of "
    "a fish eaten as food</span></span></div></span></div></div></div></div> <div id=\"other-entry-2\"><div "
    "class=\"row entry-header\"><div class=\"col\"><p class=\"hword\">fish</p> <span class=\"fl\"><em><a "
    "class=\"important-blue-link\" href=\"/dictionary/verb\">verb</a></em></span></div></div> <div "
    "class=\"row vg-header\"><div class=\"col\"><p class=\"hword2 english-learners\" "
    "data-source=\"header-learners\">English Language Learners Definition of <em>fish</em>&nbsp;(Entry 2 of "
    "2)</div></div> <div class=\"learners-def\"><div class=\"vg\"><div class=\"sb no-sn\"><span "
    "class=\"sb-0\"><div class=\"sense no-subnum\"><span class=\"dt \"><span class=\"dtText\"><strong "
    "class=\"mw_t_bc\">: </strong>to catch or try to catch fish</span></span></div></span></div> <div "
    "class=\"sb no-sn\"><span class=\"sb-0\"><div class=\"sense no-subnum\"><span class=\"dt \"><span "
    "class=\"dtText\"><strong class=\"mw_t_bc\">: </strong>to catch or try to catch fish in (a river, "
    "stream, etc.)</span></span></div></span></div> <div class=\"sb no-sn\"><span class=\"sb-0\"><div "
    "class=\"sense no-subnum\"><span class=\"dt \"><span class=\"dtText\"><strong class=\"mw_t_bc\">: "
    "</strong>to search for something by feeling <strong class=\"mw_t_bc\">: </strong>to use your hand to "
    "try to find something</span></span></div></span></div></div></div> <p class=\"ldLink\"><a "
    "href=\"http://www.learnersdictionary.com/search/fish\" rel=\"noopener\" target=\"_blank\">See the full "
    "definition for <em>fish</em> in the English Language Learners Dictionary</a></div> <div "
    "class=\"heavy-break entry\"></div> <span id=\"kidsdictionary-anchor\"></span> <div class=\"row "
    "entry-header\"><div class=\"col-12\"><p class=\"hword\">fish</p> <span class=\"fl\"><a "
    "class=\"important-blue-link\" href=\"/dictionary/noun\">noun</a></span></div></div> <div class=\"row "
    "entry-attr\"><div class=\"col\"><span class=\"prs\"><span class=\"first-slash\">\\</span><span "
    "class=\"pr\"> ˈfish</span> <a class=\"play-pron hw-play-pron\" data-lang=\"en_us\" "
    "data-file=\"fish0001\" data-dir=\"f\" "
    "href=\"https://www.merriam-webster.com/dictionary/"
    "fish?pronunciation&lang=en_us&dir=f&amp;file=fish0001\" "
    "data-url=\"https://www.merriam-webster.com/dictionary/"
    "fish?pronunciation&lang=en_us&dir=f&amp;file=fish0001\" data-title=\"How to pronounce fish (audio)\" "
    "title=\"How to pronounce fish (audio)\"><img class=\"svg\" "
    "src=\"https://merriam-webster.com/assets/mw/dist/compiled/images/svg/audio.svg\" alt=\"How to pronounce "
    "fish (audio)\"></a> <span class=\"last-slash\">\\</span></span></div></div> <div class=\"row "
    "headword-row\"><div class=\"col\"><span class=\"vg-ins\"><span class=\"il plural\"> "
    "plural&#32;</span><span class=\"if\">fish</span><span class=\"il or\"> or&#32;</span><span "
    "class=\"if\">fishes</span></span></div></div> <div id=\"elementary-entry-1\"><div class=\"row "
    "vg-header\"><div class=\"col\"><h2>Kids Definition of <em>fish</em></h2><p "
    "class=\"entryNumbers\">&nbsp;(Entry 1 of 2)</div></div> <div class=\"vg\"><div class=\"sb "
    "has-num\"><span class=\"sb-0\"><div class=\"sense has-num-only\"><span class=\"sn sense-1\"><span "
    "class=\"num\">1</span></span> <span class=\"dt \"><span class=\"dtText\"><strong class=\"mw_t_bc\">: "
    "</strong>any of a large group of vertebrate animals that live in water, breathe with gills, and usually "
    "have fins and scales</span></span></div></span></div> <div class=\"sb has-num\"><span "
    "class=\"sb-0\"><div class=\"sense has-num-only\"><span class=\"sn sense-2\"><span "
    "class=\"num\">2</span></span> <span class=\"dt \"><span class=\"dtText\"><strong class=\"mw_t_bc\">: "
    "</strong>an animal that lives in water                                      \n"
    "                <span class=\"uns\"><span class=\"un\"><span class=\"mdash\">&mdash;</span><span "
    "class=\"unText\">usually used in combination<span class=\"vis\"><span class=\"vi\"><span "
    "class=\"ex-sent first-child t no-aq sents\">star<em class=\"mw_t_it\">fish</em></span></span><span "
    "class=\"vi\"><span class=\"ex-sent  t no-aq sents\">shell<em "
    "class=\"mw_t_it\">fish</em></span></span></span></span></span></span></span></span></div></span></div></"
    "div></div> <div class=\"widget uros other-uros\"><p class=\"hword2\">Other Words from <em>fish</em> "
    "<div class=\"uro\"><span class=\"ure\">fishlike</span> <span class=\"first-slash\">\\</span> <span "
    "class=\"prt-a\"><span class=\"mw\">-&#8203;ˌlīk    </span></span> <span class=\"last-slash\">\\</span> "
    "<span class=\"fl\">adjective</span></div></div> <span class=\"anchor-spacer\"></span> <div class=\"row "
    "entry-header\"><div class=\"col-12\"><p class=\"hword\">fish</p> <span class=\"fl\"><a "
    "class=\"important-blue-link\" href=\"/dictionary/verb\">verb</a></span></div></div> <div class=\"row "
    "headword-row\"><div class=\"col\"><span class=\"vg-ins\"><span class=\"if\">fished</span><span "
    "class=\"sep-semicolon\">; </span><span class=\"if\">fishing</span></span></div></div> <div "
    "id=\"elementary-entry-2\"><div class=\"row vg-header\"><div class=\"col\"><p class=\"hword2\">Kids "
    "Definition of <em>fish</em>&nbsp;(Entry 2 of 2)</div></div> <div class=\"vg\"><div class=\"sb "
    "has-num\"><span class=\"sb-0\"><div class=\"sense has-num-only\"><span class=\"sn sense-1\"><span "
    "class=\"num\">1</span></span> <span class=\"dt \"><span class=\"dtText\"><strong class=\"mw_t_bc\">: "
    "</strong>to catch or try to catch fish</span></span></div></span></div> <div class=\"sb has-num\"><span "
    "class=\"sb-0\"><div class=\"sense has-num-only\"><span class=\"sn sense-2\"><span "
    "class=\"num\">2</span></span> <span class=\"dt \"><span class=\"dtText\"><strong class=\"mw_t_bc\">: "
    "</strong>to search for something by or as if by feeling                                      \n"
    "             \n"
    "             <span class=\"ex-sent first-child t no-aq sents\">I <em class=\"mw_t_it\">fished</em> in "
    "my purse for change.</span></span></span></div></span></div></div></div> <div class=\"heavy-break "
    "entry\"></div></div> <div class=\"d-block d-lg-none d-xl-none ads\"><p class=\"text-center disclaimer "
    "font-italic\">Keep scrolling for more <div class=\"light-break above-ads\"></div> <div class=\"abl "
    "mw-ad-slot-top abl-m320-t728-d728 mw-ad-slot-content\"></div> <div class=\"light-break "
    "below-ads\"></div></div> <div class=\"widget more-from\"><p class=\"hword2\">More from Merriam-Webster "
    "on <em>fish</em> <p>Thesaurus: <a href=\"/thesaurus/fish\">All synonyms and antonyms for "
    "<em>fish</em></a> <p>Spanish Central: <a href=\"http://www.spanishcentral.com/translate/fish\" "
    "rel=\"noopener\" target=\"_blank\">Translation of <em>fish</em></a> <p>Nglish: <a "
    "href=\"http://www.nglish.com/spanish/fish\" rel=\"noopener\" target=\"_blank\">Translation of "
    "<em>fish</em> for Spanish Speakers</a> <p>Britannica English: <a "
    "href=\"http://arabic.britannicaenglish.com/fish\" rel=\"noopener\" target=\"_blank\">Translation of "
    "<em>fish</em> for Arabic Speakers</a> <p>Britannica.com: <a "
    "href=\"http://www.britannica.com/EBchecked/topic/208456/fish\" rel=\"noopener\" "
    "target=\"_blank\">Encyclopedia article about <em>fish</em></a></div> <div class=\"widget "
    "seen-and-heard-block\"><p class=\"hword2\">Comments on <em>fish</em> <p class=\"comment-text\">What "
    "made you want to look up <em>fish</em>? Please tell us where you read or heard it (including the quote, "
    "if possible). <div class=\"toggle-fb-comments\"><a id=\"seen-and-heard-block\" class=\"widget-button "
    "comment-expand toggle-link\" href=\"#\"><span class=\"show-comment\">Show Comments&nbsp;<img "
    "class=\"svg more\" src=\"https://merriam-webster.com/assets/mw/dist/compiled/images/svg/show-more.svg\" "
    "aria-hidden=\"true\"></span> <span class=\"hide-comment\">Hide Comments&nbsp;<img class=\"svg less\" "
    "src=\"https://merriam-webster.com/assets/mw/dist/compiled/images/svg/show-less.svg\" "
    "aria-hidden=\"true\"></span></a> <div class=\"mw-loader\"></div> <div class=\"fb-comments-container\" "
    "data-href=\"http://www.merriam-webster.com/dictionary/fish\" data-numposts=\"10\" data-width=\"100%\" "
    "data-order-by=\"reverse_time\"></div></div></div></div> <div id=\"definition-right-rail\" "
    "class=\"right-rail col-lg-5 col-xl-4\"><div class=\"fixed-wrapper hash-bg\" "
    "id=\"definition-fixed-wrapper\"><div class=\"rail-abl-box\"><div class=\"abl abl-300-250-nr "
    "mw-ad-slot-right1\"></div></div> <div class=\"wgt-side wgt-wod-side top-location\"><h4 "
    "class=\"jc-wgt-title-type1 margin-t-0p9375em\"><a href=\"/word-of-the-day\">WORD OF THE DAY</a></h4> "
    "<div class=\"jc-under-tline-type2 margin-t-0p625em\"></div> <div class=\"ws-word-and-pron\"><h4 "
    "class=\"ws-word\"><a href=\"/word-of-the-day\">stymie</a></h4> <a class=\"play-pron "
    "jc-play-icon-type1\" data-lang=\"en_us\" data-dir=\"s\" data-file=\"stymie01\" "
    "href=\"javascript:void(0)\" title=\"Listen to the pronunciation of stymie\"><img class=\"svg\" "
    "alt=\"Listen to the pronunciation of stymie\" "
    "src=\"https://merriam-webster.com/assets/mw/dist/compiled/images/svg/audio.svg\"></a></div> <p "
    "class=\"ws-def-text\"><a href=\"/word-of-the-day\">See Definitions and Examples</a> &raquo;\n"
    "  <div class=\"word-of-day-subscribe-block\"><p class=\"wod-lead\">Get Word of the Day daily email! "
    "<form class=\"js-wod-subscribe-frm\" action=\"/word-of-the-day\" method=\"post\"><input type=\"submit\" "
    "class=\"wod-submit\" name=\"wod-submit\" value=\"SUBSCRIBE\"> <input type=\"text\" "
    "class=\"wod-subscribe\" name=\"wod-subscribe\" placeholder=\"Your email address\" "
    "aria-label=\"Subscribe to Word of the Day\"></form></div></div></div> <div "
    "id=\"M300250BOT-sticky-wrapper\"><div id=\"M300250BOT-sticky\" class=\"rail-abl-box hash-bg\"><div "
    "class=\"abl abl-300-250-nr mw-ad-slot-right2\"></div> <div class=\"wgt-side wgt-games-side\"><h4 "
    "class=\"jc-wgt-title-type1\"><a href=\"/word-games\">Test Your Vocabulary</a></h4> <div "
    "class=\"jc-under-tline-type2 margin-t-0p625em margin-b-1p375em\"></div> <p class=\"lead\">Name More "
    "Food! <div class=\"wgt-games-side-items\"><div class=\"wgts-quiz-with-answers\"><ul "
    "class=\"wgts-quiz-question\"><li class=\"wgts-quiz-image\"><div class=\"thumbnail\"><span "
    "class=\"lazyload-container ratio-4-3\"><img data-sizes=\"auto\" alt=\"red fruit\" is_retina=\"true\" "
    "data-src=\"https://merriam-webster.com/assets/mw/images/quiz/quiz-games-quizplay-question/"
    "red-fruit-2553-58ebae9ee81e7e44ddd4e5a038eb3123@1x.jpg\" data-caption=\"\" data-credit=\"\" "
    "data-type=\"quiz\" data-dim=\"quiz-games-quizplay-question\" "
    "data-ret-pref=\"red-fruit-2553-58ebae9ee81e7e44ddd4e5a038eb3123\" data-ret-x=\"1\" "
    "data-srcset=\"https://merriam-webster.com/assets/mw/images/quiz/quiz-games-quizplay-question/"
    "red-fruit-2553-58ebae9ee81e7e44ddd4e5a038eb3123@1x.jpg 1x, "
    "https://merriam-webster.com/assets/mw/images/quiz/quiz-games-quizplay-question/"
    "red-fruit-2553-58ebae9ee81e7e44ddd4e5a038eb3123@2x.jpg 2x\" pair-id=\"2556\" image-id=\"2553\" "
    "class=\"lazyload\" "
    "src=\"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==\"></span></div> <li "
    "class=\"lead\">Name that Fruit!</ul> <div class=\"content\"><ul class=\"quiz-answer-list\"><li><a "
    "class=\"quiz-answer\" href=\"/word-games/name-more-food?q=437&a=1717\">lingonberry</a> <a "
    "class=\"quiz-answer\" href=\"/word-games/name-more-food?q=437&a=1714\">pomegranate</a><li><a "
    "class=\"quiz-answer\" href=\"/word-games/name-more-food?q=437&a=1716\">pomelo</a> <a "
    "class=\"quiz-answer\" href=\"/word-games/name-more-food?q=437&a=1715\">jackfruit</a></ul></div></div> "
    "<div class=\"wgts-quiz\"><div class=\"thumbnail\"><span class=\"lazyload-container ratio-4-3\"><img "
    "data-sizes=\"auto\" alt=\"Spell It\" "
    "data-src=\"https://merriam-webster.com/assets/mw/static/images/old-quizzes/spell-it/80x60@1x.jpg\" "
    "data-dim=\"80x60\" "
    "data-srcset=\"https://merriam-webster.com/assets/mw/static/images/old-quizzes/spell-it/80x60@1x.jpg 1x, "
    "https://merriam-webster.com/assets/mw/static/images/old-quizzes/spell-it/80x60@2x.jpg 2x\" "
    "class=\"lazyload\" "
    "src=\"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==\"></span></div> <div "
    "class=\"content\"><p class=\"blurb\">Can you spell these 10 commonly misspelled words?</p> <a "
    "class=\"to-quiz\" href=\"/word-games/spell-it\">TAKE THE QUIZ</a></div></div> <div class=\"wgts-quiz "
    "last\"><div class=\"thumbnail\"><span class=\"lazyload-container ratio-4-3\"><img data-sizes=\"auto\" "
    "alt=\"Bee Cubed\" "
    "data-src=\"https://merriam-webster.com/assets/mw/static/images/games/special5/bee-cubed/"
    "204x153@1x.jpg\" "
    "data-srcset=\"https://merriam-webster.com/assets/mw/static/images/games/special5/bee-cubed/"
    "204x153@1x.jpg 1x, "
    "https://merriam-webster.com/assets/mw/static/images/games/special5/bee-cubed/204x153@2x.jpg 2x\" "
    "data-dim=\"204x153\" class=\"lazyload\" "
    "src=\"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==\"></span></div> <div "
    "class=\"content\"><p class=\"blurb\"><strong>Test Your Knowledge</strong> - and learn some interesting "
    "things along the way.</p> <a class=\"to-quiz\" href=\"/word-games/bee-cubed\">TAKE THE "
    "QUIZ</a></div></div></div></div></div></div></div></div> <div id=\"subscribe-unabridged\" "
    "class=\"clearfix\"><div class=\"header\">Love words? Need even more definitions?</div> <p "
    "class=\"teaser\">Subscribe to America's largest dictionary and get thousands more definitions and "
    "advanced search&mdash;ad free!</p> <a class=\"subscribe-btn\" rel=\"noopener\" target=\"_blank\" "
    "href=\"https://unabridged.merriam-webster.com/subscriber/register/"
    "p1?refc=FOOTER_DEF_MWU\">Merriam-Webster unabridged</a></div></div> <div "
    "class=\"additional-content-area\"><div class=\"additional-items\"><span class=\"items__header\">Words "
    "at Play</span> <ul><li><a href=\"/words-at-play/words-for-being-alone\"><span "
    "class=\"lazyload-container ratio-3-2\"><img data-sizes=\"auto\" alt=\"remote-cabin-in-woods\" "
    "is_retina=\"true\" "
    "data-src=\"https://merriam-webster.com/assets/mw/images/gallery/gal-global-footer-recirc/"
    "remote-cabin-in-woods-7477-8238a1d968aea9154fbdfa8d1ee7a6f7@1x.jpg\" data-caption=\"\" data-credit=\"\" "
    "data-type=\"gallery\" data-dim=\"gal-global-footer-recirc\" "
    "data-ret-pref=\"remote-cabin-in-woods-7477-8238a1d968aea9154fbdfa8d1ee7a6f7\" data-ret-x=\"1\" "
    "data-srcset=\"https://merriam-webster.com/assets/mw/images/gallery/gal-global-footer-recirc/"
    "remote-cabin-in-woods-7477-8238a1d968aea9154fbdfa8d1ee7a6f7@1x.jpg 1x, "
    "https://merriam-webster.com/assets/mw/images/gallery/gal-global-footer-recirc/"
    "remote-cabin-in-woods-7477-8238a1d968aea9154fbdfa8d1ee7a6f7@2x.jpg 2x\" pair-id=\"7479\" "
    "image-id=\"7477\" class=\"lazyload\" "
    "src=\"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==\"></span></a> <span "
    "class=\"item__title\"><a href=\"/words-at-play/words-for-being-alone\">Words for Being Alone</a></span> "
    "<p class=\"mell-gr235\"><a href=\"/words-at-play/words-for-being-alone\">Keep company with words of "
    "solitude</a> <li><a href=\"/words-at-play/words-were-watching-infodemic-meaning\"><span "
    "class=\"lazyload-container ratio-3-2\"><img data-sizes=\"auto\" alt=\"news-news-news-graphic\" "
    "is_retina=\"true\" "
    "data-src=\"https://merriam-webster.com/assets/mw/images/article/art-global-footer-recirc/"
    "news-news-news-graphic-7476-c36c529ca203eb72333f5aaf9772f2d0@1x.jpg\" data-caption=\"\" "
    "data-credit=\"\" data-type=\"article\" data-dim=\"art-global-footer-recirc\" "
    "data-ret-pref=\"news-news-news-graphic-7476-c36c529ca203eb72333f5aaf9772f2d0\" data-ret-x=\"1\" "
    "data-srcset=\"https://merriam-webster.com/assets/mw/images/article/art-global-footer-recirc/"
    "news-news-news-graphic-7476-c36c529ca203eb72333f5aaf9772f2d0@1x.jpg 1x, "
    "https://merriam-webster.com/assets/mw/images/article/art-global-footer-recirc/"
    "news-news-news-graphic-7476-c36c529ca203eb72333f5aaf9772f2d0@2x.jpg 2x\" pair-id=\"7478\" "
    "image-id=\"7476\" class=\"lazyload\" "
    "src=\"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==\"></span></a> <span "
    "class=\"item__title\"><a href=\"/words-at-play/words-were-watching-infodemic-meaning\">Words We're "
    "Watching: 'Infodemic'</a></span> <p class=\"mell-gr235\"><a "
    "href=\"/words-at-play/words-were-watching-infodemic-meaning\">Here's a reasonable amount of "
    "explanation.</a> <li><a href=\"/words-at-play/plague-word-history-literary-metaphor\"><span "
    "class=\"lazyload-container ratio-3-2\"><img data-sizes=\"auto\" alt=\"stethoscope-with-cutout-people\" "
    "is_retina=\"true\" "
    "data-src=\"https://merriam-webster.com/assets/mw/images/article/art-global-footer-recirc/"
    "stethoscope-with-cutout-people-7474-6788318cd3404a0cc98f8288166ad60e@1x.jpg\" data-caption=\"\" "
    "data-credit=\"\" data-type=\"article\" data-dim=\"art-global-footer-recirc\" "
    "data-ret-pref=\"stethoscope-with-cutout-people-7474-6788318cd3404a0cc98f8288166ad60e\" data-ret-x=\"1\" "
    "data-srcset=\"https://merriam-webster.com/assets/mw/images/article/art-global-footer-recirc/"
    "stethoscope-with-cutout-people-7474-6788318cd3404a0cc98f8288166ad60e@1x.jpg 1x, "
    "https://merriam-webster.com/assets/mw/images/article/art-global-footer-recirc/"
    "stethoscope-with-cutout-people-7474-6788318cd3404a0cc98f8288166ad60e@2x.jpg 2x\" pair-id=\"7476\" "
    "image-id=\"7474\" class=\"lazyload\" "
    "src=\"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==\"></span></a> <span "
    "class=\"item__title\"><a href=\"/words-at-play/plague-word-history-literary-metaphor\">A History of "
    "‘Plague’: Illness as Metaphor</a></span> <p class=\"mell-gr235\"><a "
    "href=\"/words-at-play/plague-word-history-literary-metaphor\">From the Bible to COVID-19</a> <li><a "
    "href=\"/words-at-play/descriptive-vs-prescriptive-defining-lexicography\"><span "
    "class=\"lazyload-container ratio-3-2\"><img data-sizes=\"auto\" alt=\"open-dictionary\" "
    "is_retina=\"true\" "
    "data-src=\"https://merriam-webster.com/assets/mw/images/article/art-global-footer-recirc/"
    "open-dictionary-7470-50fc5466bed669d061e993646bd6086b@1x.jpg\" data-caption=\"\" data-credit=\"\" "
    "data-type=\"article\" data-dim=\"art-global-footer-recirc\" "
    "data-ret-pref=\"open-dictionary-7470-50fc5466bed669d061e993646bd6086b\" data-ret-x=\"1\" "
    "data-srcset=\"https://merriam-webster.com/assets/mw/images/article/art-global-footer-recirc/"
    "open-dictionary-7470-50fc5466bed669d061e993646bd6086b@1x.jpg 1x, "
    "https://merriam-webster.com/assets/mw/images/article/art-global-footer-recirc/"
    "open-dictionary-7470-50fc5466bed669d061e993646bd6086b@2x.jpg 2x\" pair-id=\"7472\" image-id=\"7470\" "
    "class=\"lazyload\" "
    "src=\"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==\"></span></a> <span "
    "class=\"item__title\"><a href=\"/words-at-play/descriptive-vs-prescriptive-defining-lexicography\">A "
    "Word on 'Descriptive' and 'Prescriptive' Defining</a></span> <p class=\"mell-gr235\"><a "
    "href=\"/words-at-play/descriptive-vs-prescriptive-defining-lexicography\">When it comes to words, we're "
    "descriptive. </a></ul></div> <div class=\"additional-items\"><span class=\"items__header\">Ask the "
    "Editors</span> <ul><li><a href=\"/video/how-to-spell-definitely\"><span class=\"lazyload-container "
    "ratio-3-2\"><img data-sizes=\"auto\" alt=\"serenity-carr-definitely-image\" is_retina=\"true\" "
    "data-src=\"https://merriam-webster.com/assets/mw/images/video/vid-global-footer-recirc/"
    "serenity-carr-definitely-image-7386-58c32cb72643032ee627341e2c9a29fe@1x.jpg\" data-caption=\"\" "
    "data-credit=\"\" data-type=\"video\" data-dim=\"vid-global-footer-recirc\" "
    "data-ret-pref=\"serenity-carr-definitely-image-7386-58c32cb72643032ee627341e2c9a29fe\" data-ret-x=\"1\" "
    "data-srcset=\"https://merriam-webster.com/assets/mw/images/video/vid-global-footer-recirc/"
    "serenity-carr-definitely-image-7386-58c32cb72643032ee627341e2c9a29fe@1x.jpg 1x, "
    "https://merriam-webster.com/assets/mw/images/video/vid-global-footer-recirc/"
    "serenity-carr-definitely-image-7386-58c32cb72643032ee627341e2c9a29fe@2x.jpg 2x\" pair-id=\"7388\" "
    "image-id=\"7386\" class=\"lazyload\" "
    "src=\"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==\"></span></a> <span "
    "class=\"item__title\"><a href=\"/video/how-to-spell-definitely\">How to Remember the Spelling of "
    "'Definitely'</a></span> <p class=\"mell-gr235\"><a href=\"/video/how-to-spell-definitely\">A definitive "
    "answer.</a> <li><a href=\"/video/why-is-there-a-c-in-indict\"><span class=\"lazyload-container "
    "ratio-3-2\"><img data-sizes=\"auto\" alt=\"peter-sokolowski-indict-graphic\" is_retina=\"true\" "
    "data-src=\"https://merriam-webster.com/assets/mw/images/video/vid-global-footer-recirc/"
    "peter-sokolowski-indict-graphic-7371-33e42b2207a8be37bfb5da7471e36111@1x.jpg\" data-caption=\"\" "
    "data-credit=\"\" data-type=\"video\" data-dim=\"vid-global-footer-recirc\" "
    "data-ret-pref=\"peter-sokolowski-indict-graphic-7371-33e42b2207a8be37bfb5da7471e36111\" "
    "data-ret-x=\"1\" "
    "data-srcset=\"https://merriam-webster.com/assets/mw/images/video/vid-global-footer-recirc/"
    "peter-sokolowski-indict-graphic-7371-33e42b2207a8be37bfb5da7471e36111@1x.jpg 1x, "
    "https://merriam-webster.com/assets/mw/images/video/vid-global-footer-recirc/"
    "peter-sokolowski-indict-graphic-7371-33e42b2207a8be37bfb5da7471e36111@2x.jpg 2x\" pair-id=\"7373\" "
    "image-id=\"7371\" class=\"lazyload\" "
    "src=\"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==\"></span></a> <span "
    "class=\"item__title\"><a href=\"/video/why-is-there-a-c-in-indict\">Video: Why Is There a 'C' in "
    "'Indict'?</a></span> <p class=\"mell-gr235\"><a href=\"/video/why-is-there-a-c-in-indict\">And who put "
    "it there, anyway?</a> <li><a href=\"/video/literally\"><span class=\"lazyload-container "
    "ratio-3-2\"><img data-sizes=\"auto\" alt=\"video literally\" is_retina=\"true\" "
    "data-src=\"https://merriam-webster.com/assets/mw/images/video/vid-global-footer-recirc/"
    "video-literally-1143@1x.jpg\" data-caption=\"\" data-credit=\"\" data-type=\"video\" "
    "data-dim=\"vid-global-footer-recirc\" data-ret-pref=\"video-literally-1143\" data-ret-x=\"1\" "
    "data-srcset=\"https://merriam-webster.com/assets/mw/images/video/vid-global-footer-recirc/"
    "video-literally-1143@1x.jpg 1x, "
    "https://merriam-webster.com/assets/mw/images/video/vid-global-footer-recirc/video-literally-1143@2x.jpg "
    "2x\" pair-id=\"1145\" image-id=\"1143\" class=\"lazyload\" "
    "src=\"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==\"></span></a> <span "
    "class=\"item__title\"><a href=\"/video/literally\">Literally</a></span> <p class=\"mell-gr235\"><a "
    "href=\"/video/literally\">How to use a word that (literally) drives some people nuts.</a> <li><a "
    "href=\"/video/the-awkward-case-of-his-or-her\"><span class=\"lazyload-container ratio-3-2\"><img "
    "data-sizes=\"auto\" alt=\"video his or her\" is_retina=\"true\" "
    "data-src=\"https://merriam-webster.com/assets/mw/images/video/vid-global-footer-recirc/"
    "video-his-or-her-1148@1x.jpg\" data-caption=\"\" data-credit=\"\" data-type=\"video\" "
    "data-dim=\"vid-global-footer-recirc\" data-ret-pref=\"video-his-or-her-1148\" data-ret-x=\"1\" "
    "data-srcset=\"https://merriam-webster.com/assets/mw/images/video/vid-global-footer-recirc/"
    "video-his-or-her-1148@1x.jpg 1x, "
    "https://merriam-webster.com/assets/mw/images/video/vid-global-footer-recirc/"
    "video-his-or-her-1148@2x.jpg 2x\" pair-id=\"1150\" image-id=\"1148\" class=\"lazyload\" "
    "src=\"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==\"></span></a> <span "
    "class=\"item__title\"><a href=\"/video/the-awkward-case-of-his-or-her\">Is Singular 'They' a Better "
    "Choice?</a></span> <p class=\"mell-gr235\"><a href=\"/video/the-awkward-case-of-his-or-her\">The "
    "awkward case of 'his or her'</a></ul></div> <div class=\"additional-items\"><span "
    "class=\"items__header\">Word Games</span> <ul><li><a href=\"/word-games/name-more-food\"><span "
    "class=\"lazyload-container ratio-3-2\"><img data-sizes=\"auto\" alt=\"name more food\" "
    "is_retina=\"true\" "
    "data-src=\"https://merriam-webster.com/assets/mw/images/quiz/quiz-global-footer-recirc/"
    "name-more-food-2559-6a44b579070df511f5e499a5a112678b@1x.jpg\" data-caption=\"\" data-credit=\"\" "
    "data-type=\"quiz\" data-dim=\"quiz-global-footer-recirc\" "
    "data-ret-pref=\"name-more-food-2559-6a44b579070df511f5e499a5a112678b\" data-ret-x=\"1\" "
    "data-srcset=\"https://merriam-webster.com/assets/mw/images/quiz/quiz-global-footer-recirc/"
    "name-more-food-2559-6a44b579070df511f5e499a5a112678b@1x.jpg 1x, "
    "https://merriam-webster.com/assets/mw/images/quiz/quiz-global-footer-recirc/"
    "name-more-food-2559-6a44b579070df511f5e499a5a112678b@2x.jpg 2x\" pair-id=\"2562\" image-id=\"2559\" "
    "class=\"lazyload\" "
    "src=\"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==\"></span></a> <span "
    "class=\"item__title\"><a href=\"/word-games/name-more-food\">Name More Food!</a></span> <p "
    "class=\"mell-gr235\"><a href=\"/word-games/name-more-food\">Test your knowledge of food "
    "vocabulary!</a></p> <a class=\"quiz-link\" href=\"/word-games/name-more-food\">Take the quiz</a> <li><a "
    "href=\"/word-games/april-2020-wotd-quiz\"><span class=\"lazyload-container ratio-3-2\"><img "
    "data-sizes=\"auto\" alt=\"ludwig richter spring has arrived\" is_retina=\"true\" "
    "data-src=\"https://merriam-webster.com/assets/mw/images/quiz/quiz-global-footer-recirc/"
    "ludwig-richter-spring-has-arrived-3614-04105e24fdadc54de66b929bdb90b96a@1x.jpg\" data-caption=\"\" "
    "data-credit=\"Ludwig Richter (German, 1803 - 1884) Spring Has Arrived, 1870, Watercolor, graphite, "
    "gouache and touches of red chalk 20.4 x 16.7 cm (8 1/16 x 6 9/16 in.) The J. Paul Getty Museum, Los "
    "Angeles\" data-type=\"quiz\" data-dim=\"quiz-global-footer-recirc\" "
    "data-ret-pref=\"ludwig-richter-spring-has-arrived-3614-04105e24fdadc54de66b929bdb90b96a\" "
    "data-ret-x=\"1\" "
    "data-srcset=\"https://merriam-webster.com/assets/mw/images/quiz/quiz-global-footer-recirc/"
    "ludwig-richter-spring-has-arrived-3614-04105e24fdadc54de66b929bdb90b96a@1x.jpg 1x, "
    "https://merriam-webster.com/assets/mw/images/quiz/quiz-global-footer-recirc/"
    "ludwig-richter-spring-has-arrived-3614-04105e24fdadc54de66b929bdb90b96a@2x.jpg 2x\" pair-id=\"3617\" "
    "image-id=\"3614\" class=\"lazyload\" "
    "src=\"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==\"></span></a> <span "
    "class=\"item__title\"><a href=\"/word-games/april-2020-wotd-quiz\">April 2020 Words of the Day "
    "Quiz</a></span> <p class=\"mell-gr235\"><a href=\"/word-games/april-2020-wotd-quiz\">Reminding you that "
    "time is, indeed, passing.</a></p> <a class=\"quiz-link\" href=\"/word-games/april-2020-wotd-quiz\">Take "
    "the quiz</a> <li><a href=\"/word-games/spell-it\"><span class=\"lazyload-container ratio-3-2\"><img "
    "data-sizes=\"auto\" alt=\"Spell It\" "
    "data-src=\"https://merriam-webster.com/assets/mw/static/images/old-quizzes/spell-it/261x174@1x.jpg\" "
    "data-dim=\"261x174\" "
    "data-srcset=\"https://merriam-webster.com/assets/mw/static/images/old-quizzes/spell-it/261x174@1x.jpg "
    "1x, https://merriam-webster.com/assets/mw/static/images/old-quizzes/spell-it/261x174@2x.jpg 2x\" "
    "class=\"lazyload\" "
    "src=\"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==\"></span></a> <span "
    "class=\"item__title\"><a href=\"/word-games/spell-it\">Spell It</a></span> <p class=\"mell-gr235\"><a "
    "href=\"/word-games/spell-it\">Can you spell these 10 commonly misspelled words?</a></p> <a "
    "class=\"quiz-link\" href=\"/word-games/spell-it\">Take the quiz</a> <li><a "
    "href=\"/word-games/bee-cubed\"><span class=\"lazyload-container ratio-3-2\"><img data-sizes=\"auto\" "
    "alt=\"Bee Cubed\" "
    "data-src=\"https://merriam-webster.com/assets/mw/static/images/games/special5/bee-cubed/"
    "261x174@1x.jpg\" "
    "data-srcset=\"https://merriam-webster.com/assets/mw/static/images/games/special5/bee-cubed/"
    "261x174@1x.jpg 1x, "
    "https://merriam-webster.com/assets/mw/static/images/games/special5/bee-cubed/261x174@2x.jpg 2x\" "
    "data-dim=\"261x174\" class=\"lazyload\" "
    "src=\"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==\"></span></a> <span "
    "class=\"item__title\"><a href=\"/word-games/bee-cubed\">Bee Cubed</a></span> <p class=\"mell-gr235\"><a "
    "href=\"/word-games/bee-cubed\">Listen to the words and spell through all three levels.</a></p> <a "
    "class=\"quiz-link\" href=\"/word-games/bee-cubed\">Play the game</a></ul></div></div> <div "
    "class=\"border-box mobile-fixed-ad d-lg-none\"><div class=\"abl abl-m320-t728-d728\"><div "
    "id=\"mw-ad-slot-mobile-fixed-ad\"></div></div></div> "
    "<script>window.mwdata.firstHwFound=\"fish\";window.mwdata.time=\"1589528003\";window.mwdata.rp="
    "encodeURIComponent(\"dictionary\");window.mwdata.usp=encodeURIComponent(\"fish\");</script> <footer "
    "class=\"global-footer \"><div class=\"footer-mast clearfix\"><div class=\"mw-logo-section lazyload\"><a "
    "href=\"/\" class=\"footer-logo\">Merriam Webster</a></div> <div class=\"footer-mast-content "
    "clearfix\"><div class=\"footer-subscribe-block\"><div class=\"footer-subscribe-msg\"><p>Learn a new "
    "word every day. Delivered to your inbox!</div> <form data-medium=\"footer\" class=\"footer-subscribe "
    "js-wod-subscribe-frm\"><input class=\"footer-subscribe-field\" type=\"text\" name=\"email\" "
    "aria-label=\"Sign up for Merriam-Webster's Word of the Day newsletter\" placeholder=\"Your email "
    "address\"> <input class=\"footer-subscribe-button\" type=\"submit\" name=\"submit\" "
    "aria-label=\"Subscribe\" value=\"SUBSCRIBE\"> <input class=\"footer-subscribe-button hidden arrow\" "
    "type=\"submit\" name=\"submit\" value=\"&gt;\"></form></div> <div "
    "class=\"footer-dictionaries\"><p>OTHER MERRIAM-WEBSTER DICTIONARIES <div "
    "class=\"other-dictionaries\"><ul><li><a href=\"http://www.spanishcentral.com/\">SPANISH CENTRAL</a> "
    "<li><a href=\"http://learnersdictionary.com/\">LEARNER'S ESL DICTIONARY</a> <li><a "
    "href=\"http://www.wordcentral.com/\">WORDCENTRAL FOR KIDS</a> <li><a "
    "href=\"http://www.visualdictionaryonline.com/\">VISUAL DICTIONARY</a></ul> <ul><li><a "
    "href=\"http://scrabble.merriam.com/\">SCRABBLE<sup>&reg;</sup> WORD FINDER</a> <li><a "
    "href=\"http://unabridged.merriam-webster.com/\">MERRIAM-WEBSTER'S UNABRIDGED DICTIONARY</a> <li><a "
    "href=\"http://arabic.britannicaenglish.com/en\">BRITANNICA ENGLISH - ARABIC TRANSLATION</a> <li><a "
    "href=\"http://www.nglish.com/spanish/en/\">NGLISH - SPANISH-ENGLISH TRANSLATION</a></ul></div></div> "
    "<div class=\"follow-us lazyload\"><p>FOLLOW US <div class=\"follow-links\"><ul><li><a "
    "href=\"https://www.facebook.com/merriamwebster\" rel=\"noopener\" target=\"_blank\" class=\"social-link "
    "social-fb\">Facebook</a> <li><a href=\"https://twitter.com/merriamwebster\" rel=\"noopener\" "
    "target=\"_blank\" class=\"social-link social-tw\">Twitter</a> <li><a "
    "href=\"https://www.youtube.com/user/MerriamWebsterOnline\" rel=\"noopener\" target=\"_blank\" "
    "class=\"social-link social-play\">YouTube</a> <li><a href=\"https://www.instagram.com/merriamwebster/\" "
    "rel=\"noopener\" target=\"_blank\" class=\"social-link "
    "social-ig\">Instagram</a></ul></div></div></div></div> <div class=\"footer-foot clearfix "
    "footer-oa\"><div class=\"footer-foot-content clearfix\"><ul class=\"footer-menu "
    "browse-dictionary\"><li><a href=\"/browse/dictionary/a\">Browse the Dictionary:</a> <li><a "
    "href=\"/browse/dictionary/a\">a</a> <li><a href=\"/browse/dictionary/b\">b</a> <li><a "
    "href=\"/browse/dictionary/c\">c</a> <li><a href=\"/browse/dictionary/d\">d</a> <li><a "
    "href=\"/browse/dictionary/e\">e</a> <li><a href=\"/browse/dictionary/f\">f</a> <li><a "
    "href=\"/browse/dictionary/g\">g</a> <li><a href=\"/browse/dictionary/h\">h</a> <li><a "
    "href=\"/browse/dictionary/i\">i</a> <li><a href=\"/browse/dictionary/j\">j</a> <li><a "
    "href=\"/browse/dictionary/k\">k</a> <li><a href=\"/browse/dictionary/l\">l</a> <li><a "
    "href=\"/browse/dictionary/m\">m</a> <li><a href=\"/browse/dictionary/n\">n</a> <li><a "
    "href=\"/browse/dictionary/o\">o</a> <li><a href=\"/browse/dictionary/p\">p</a> <li><a "
    "href=\"/browse/dictionary/q\">q</a> <li><a href=\"/browse/dictionary/r\">r</a> <li><a "
    "href=\"/browse/dictionary/s\">s</a> <li><a href=\"/browse/dictionary/t\">t</a> <li><a "
    "href=\"/browse/dictionary/u\">u</a> <li><a href=\"/browse/dictionary/v\">v</a> <li><a "
    "href=\"/browse/dictionary/w\">w</a> <li><a href=\"/browse/dictionary/x\">x</a> <li><a "
    "href=\"/browse/dictionary/y\">y</a> <li><a href=\"/browse/dictionary/z\">z</a> <li><a "
    "href=\"/browse/dictionary/0\">0-9</a></ul> <ul class=\"footer-menu\"><li><a href=\"/\">Home <span "
    "class=\"rborder\"></span></a> <li><a href=\"/help\">Help <span class=\"rborder\"></span></a> <li><a "
    "href=\"/apps\">Apps <span class=\"rborder\"></span></a> <li><a href=\"/about-us\">About Us <span "
    "class=\"rborder\"></span></a> <li><a href=\"/shop-dictionaries\">Shop <span "
    "class=\"rborder\"></span></a> <li><a href=\"/advertising\">Advertising Info <span "
    "class=\"rborder\"></span></a> <li><a href=\"https://www.dictionaryapi.com/\" rel=\"noopener\" "
    "target=\"_blank\">Dictionary API <span class=\"rborder\"></span></a> <li><a "
    "href=\"/contact-us\">Contact Us <span class=\"rborder\"></span></a> <li><a "
    "href=\"https://unabridged.merriam-webster.com/subscriber/register/p1?HDR_GLOBAL_JOINMWU\" "
    "rel=\"noopener\" target=\"_blank\">Join MWU <span class=\"rborder\"></span></a> <li><a "
    "href=\"/video\">Video <span class=\"rborder\"></span></a> <li><a "
    "href=\"/words-at-play/word-of-the-year\">Word of the Year <span class=\"rborder\"></span></a> <li><a "
    "href=\"/puku/about\">Puku <span class=\"rborder\"></span></a> <li><a "
    "href=\"/vocabulary/see-all\">Vocabulary Resources <span class=\"rborder\"></span></a> <li><a "
    "href=\"/legal\">Law Dictionary <span class=\"rborder\"></span></a> <li><a href=\"/medical\">Medical "
    "Dictionary <span class=\"rborder\"></span></a> <li><a href=\"/privacy-policy\">Privacy Policy <span "
    "class=\"rborder\"></span></a> <li><a href=\"/terms-of-use\">Terms of Use <span "
    "class=\"rborder\"></span></a> <li class=\"last\"><a href=\"#\" id=\"doNotSell\">Do Not Sell My "
    "Info</a></ul> <ul class=\"footer-menu\"><li><a href=\"/browse/thesaurus/a\">Browse the Thesaurus <span "
    "class=\"rborder\"></span></a> <li><a href=\"/browse/medical/a\">Browse the Medical Dictionary<span "
    "class=\"rborder\"></span></a> <li><a href=\"/browse/legal/a\">Browse the Legal Dictionary<span "
    "class=\"rborder\"></span></a> <li class=\"last\"><a href=\"http://www.spanishcentral.com/browse/a\" "
    "rel=\"noopener\" target=\"_blank\">Browse the Spanish-English Dictionary</a></ul> <p "
    "class=\"copyright\">© 2020 Merriam-Webster, Incorporated</div></div></footer></div></div> <div "
    "class=\"recirc-card\" id=\"recirc-bar-footer\"><div class=\"recirc-close\"><span "
    "class=\"iconx\"></span></div> <a class=\"recirc-item\" "
    "href=\"/words-at-play/words-for-being-alone\"><div class=\"recirc-header\">Learn More from M-W <span "
    "class=\"imgarrow\"></span></div> <div class=\"recirc-content\"><div class=\"recirc-img\"><span "
    "class=\"lazyload-container ratio-3-2\"><img data-sizes=\"auto\" alt=\"remote-cabin-in-woods\" "
    "is_retina=\"true\" "
    "data-src=\"https://merriam-webster.com/assets/mw/images/gallery/gal-global-footer-recirc/"
    "remote-cabin-in-woods-7477-8238a1d968aea9154fbdfa8d1ee7a6f7@1x.jpg\" data-caption=\"\" data-credit=\"\" "
    "data-type=\"gallery\" data-dim=\"gal-global-footer-recirc\" "
    "data-ret-pref=\"remote-cabin-in-woods-7477-8238a1d968aea9154fbdfa8d1ee7a6f7\" data-ret-x=\"1\" "
    "data-srcset=\"https://merriam-webster.com/assets/mw/images/gallery/gal-global-footer-recirc/"
    "remote-cabin-in-woods-7477-8238a1d968aea9154fbdfa8d1ee7a6f7@1x.jpg 1x, "
    "https://merriam-webster.com/assets/mw/images/gallery/gal-global-footer-recirc/"
    "remote-cabin-in-woods-7477-8238a1d968aea9154fbdfa8d1ee7a6f7@2x.jpg 2x\" pair-id=\"7479\" "
    "image-id=\"7477\" class=\"lazyload\" "
    "src=\"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==\"></span></div> <h5 "
    "class=\"recirc-title\">Words for Being Alone</h5></div></a> <a class=\"recirc-item\" "
    "href=\"/words-at-play/words-were-watching-infodemic-meaning\"><div class=\"recirc-header\">Learn More "
    "from M-W <span class=\"imgarrow\"></span></div> <div class=\"recirc-content\"><div "
    "class=\"recirc-img\"><span class=\"lazyload-container ratio-3-2\"><img data-sizes=\"auto\" "
    "alt=\"news-news-news-graphic\" is_retina=\"true\" "
    "data-src=\"https://merriam-webster.com/assets/mw/images/article/art-global-footer-recirc/"
    "news-news-news-graphic-7476-c36c529ca203eb72333f5aaf9772f2d0@1x.jpg\" data-caption=\"\" "
    "data-credit=\"\" data-type=\"article\" data-dim=\"art-global-footer-recirc\" "
    "data-ret-pref=\"news-news-news-graphic-7476-c36c529ca203eb72333f5aaf9772f2d0\" data-ret-x=\"1\" "
    "data-srcset=\"https://merriam-webster.com/assets/mw/images/article/art-global-footer-recirc/"
    "news-news-news-graphic-7476-c36c529ca203eb72333f5aaf9772f2d0@1x.jpg 1x, "
    "https://merriam-webster.com/assets/mw/images/article/art-global-footer-recirc/"
    "news-news-news-graphic-7476-c36c529ca203eb72333f5aaf9772f2d0@2x.jpg 2x\" pair-id=\"7478\" "
    "image-id=\"7476\" class=\"lazyload\" "
    "src=\"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==\"></span></div> <h5 "
    "class=\"recirc-title\">Words We're Watching: 'Infodemic'</h5></div></a> <a class=\"recirc-item\" "
    "href=\"https://www.merriam-webster.com/puku/about\"><div class=\"recirc-header\">Learn More from M-W "
    "<span class=\"imgarrow\"></span></div> <div class=\"recirc-content\"><div class=\"recirc-img\"><span "
    "class=\"lazyload-container ratio-3-2\"><img data-sizes=\"auto\" alt=\"alt-5e8c995877f72\" "
    "is_retina=\"true\" "
    "data-src=\"https://merriam-webster.com/assets/mw/images/article/art-global-footer-recirc/"
    "alt-5e8c995877f72-7368-7fa0b91503d0e0d86aae0ec2ba1ffd6d@1x.jpg\" data-caption=\"\" data-credit=\"\" "
    "data-type=\"article\" data-dim=\"art-global-footer-recirc\" "
    "data-ret-pref=\"alt-5e8c995877f72-7368-7fa0b91503d0e0d86aae0ec2ba1ffd6d\" data-ret-x=\"1\" "
    "data-srcset=\"https://merriam-webster.com/assets/mw/images/article/art-global-footer-recirc/"
    "alt-5e8c995877f72-7368-7fa0b91503d0e0d86aae0ec2ba1ffd6d@1x.jpg 1x, "
    "https://merriam-webster.com/assets/mw/images/article/art-global-footer-recirc/"
    "alt-5e8c995877f72-7368-7fa0b91503d0e0d86aae0ec2ba1ffd6d@2x.jpg 2x\" pair-id=\"7370\" image-id=\"7368\" "
    "class=\"lazyload\" "
    "src=\"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==\"></span></div> <h5 "
    "class=\"recirc-title\">Help Your Kids Build Their Vocabulary At Home</h5></div></a> <a "
    "class=\"recirc-item\" href=\"/words-at-play/epidemic-vs-pandemic-difference\"><div "
    "class=\"recirc-header\">Learn More from M-W <span class=\"imgarrow\"></span></div> <div "
    "class=\"recirc-content\"><div class=\"recirc-img\"><span class=\"lazyload-container ratio-3-2\"><img "
    "data-sizes=\"auto\" alt=\"washing-hands\" is_retina=\"true\" "
    "data-src=\"https://merriam-webster.com/assets/mw/images/article/art-global-footer-recirc/"
    "washing-hands-7282-3b0b068f273df872c8fa5ce15d08ae72@1x.jpg\" data-caption=\"\" data-credit=\"\" "
    "data-type=\"article\" data-dim=\"art-global-footer-recirc\" "
    "data-ret-pref=\"washing-hands-7282-3b0b068f273df872c8fa5ce15d08ae72\" data-ret-x=\"1\" "
    "data-srcset=\"https://merriam-webster.com/assets/mw/images/article/art-global-footer-recirc/"
    "washing-hands-7282-3b0b068f273df872c8fa5ce15d08ae72@1x.jpg 1x, "
    "https://merriam-webster.com/assets/mw/images/article/art-global-footer-recirc/"
    "washing-hands-7282-3b0b068f273df872c8fa5ce15d08ae72@2x.jpg 2x\" pair-id=\"7284\" image-id=\"7282\" "
    "class=\"lazyload\" "
    "src=\"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==\"></span></div> <h5 "
    "class=\"recirc-title\">'Pandemic' vs 'Epidemic'</h5></div></a> <a class=\"recirc-item\" "
    "href=\"/video/how-to-spell-definitely\"><div class=\"recirc-header\">Learn More from M-W <span "
    "class=\"imgarrow\"></span></div> <div class=\"recirc-content\"><div class=\"recirc-img\"><span "
    "class=\"lazyload-container ratio-3-2\"><img data-sizes=\"auto\" alt=\"serenity-carr-definitely-image\" "
    "is_retina=\"true\" "
    "data-src=\"https://merriam-webster.com/assets/mw/images/video/vid-global-footer-recirc/"
    "serenity-carr-definitely-image-7386-58c32cb72643032ee627341e2c9a29fe@1x.jpg\" data-caption=\"\" "
    "data-credit=\"\" data-type=\"video\" data-dim=\"vid-global-footer-recirc\" "
    "data-ret-pref=\"serenity-carr-definitely-image-7386-58c32cb72643032ee627341e2c9a29fe\" data-ret-x=\"1\" "
    "data-srcset=\"https://merriam-webster.com/assets/mw/images/video/vid-global-footer-recirc/"
    "serenity-carr-definitely-image-7386-58c32cb72643032ee627341e2c9a29fe@1x.jpg 1x, "
    "https://merriam-webster.com/assets/mw/images/video/vid-global-footer-recirc/"
    "serenity-carr-definitely-image-7386-58c32cb72643032ee627341e2c9a29fe@2x.jpg 2x\" pair-id=\"7388\" "
    "image-id=\"7386\" class=\"lazyload\" "
    "src=\"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==\"></span></div> <h5 "
    "class=\"recirc-title\">How to Remember the Spelling of 'Definitely'</h5></div></a></div> <script defer "
    "src=\"https://cdn.cookielaw.org/scripttemplates/otSDKStub.js\" charset=\"UTF-8\" "
    "data-domain-script=\"dd9ed1ba-5fcf-4664-a027-b6a74fa0d2a6\"></script> <script>document.cookie = "
    "\"usprivacy=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;\";</script> "
    "<script>window.LOADED_BANNER_CSS = true;</script> <link rel=\"stylesheet\" "
    "href=\"https://merriam-webster.com/assets/mw/dist/compiled/css/"
    "style-onetrust.1800c213ec7fc354aff1.css\" media=\"screen\">";